### ISSUE TITLE
 java.lang.ClassNotFoundException: Didn't find class "io.realm.DefaultRealmModuleMediator"

### ISSUE THREAD

**Issue by yoavst** [realm/realm-java#1179]
Getting this error from calling Realm.getInstance(context) on Android 5.0.2

> 06-03 15:20:16.530    1457-1457/com.yoavst.musicstats E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.yoavst.musicstats, PID: 1457
    java.lang.ExceptionInInitializerError
            at com.yoavst.musicstats.services.MusicListenerService$callback$1.onMetadataChanged(MusicListenerService.kt:111)
            at android.media.session.MediaController$MessageHandler.handleMessage(MediaController.java:1077)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: io.realm.exceptions.RealmException: Could not find io.realm.DefaultRealmModuleMediator
            at io.realm.Realm.getDefaultMediator(Realm.java:256)
            at io.realm.Realm.<clinit>(Realm.java:165)
            at com.yoavst.musicstats.services.MusicListenerService$callback$1.onMetadataChanged(MusicListenerService.kt:111)
            at android.media.session.MediaController$MessageHandler.handleMessage(MediaController.java:1077)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.ClassNotFoundException: io.realm.DefaultRealmModuleMediator
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at io.realm.Realm.getDefaultMediator(Realm.java:251)
            at io.realm.Realm.<clinit>(Realm.java:165)
            at com.yoavst.musicstats.services.MusicListenerService$callback$1.onMetadataChanged(MusicListenerService.kt:111)
            at android.media.session.MediaController$MessageHandler.handleMessage(MediaController.java:1077)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.DefaultRealmModuleMediator" on path: DexPathList[[zip file "/data/app/com.yoavst.musicstats-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yoavst.musicstats-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at io.realm.Realm.getDefaultMediator(Realm.java:251)
            at io.realm.Realm.<clinit>(Realm.java:165)
            at com.yoavst.musicstats.services.MusicListenerService$callback$1.onMetadataChanged(MusicListenerService.kt:111)
            at android.media.session.MediaController$MessageHandler.handleMessage(MediaController.java:1077)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
    Suppressed: java.lang.ClassNotFoundException: io.realm.DefaultRealmModuleMediator
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 16 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by cmelchior** [comment]
Hi @yoavst 
It sounds like the annotation processor isn't running for some reason. Are you using Android Studio or Eclipse?

**Comment by yoavst** [comment]
Android Studio.My realmObject classes are based on the kotlin example:
```kotlin
public RealmClass open class Album(
        public PrimaryKey open var id: Int = 0,
        public Index open var name: String = "",
        public open var artist: Int = 0
) : RealmObject() {
    companion object {
        public val FieldName: String = "name"
        private val UnknownName: String = "Unknown"
        public fun getUnknown(context: Context): Int {
            val realm = Realm.getInstance(context)
            var unknown = realm.where(javaClass<Album>()).equalTo(FieldName, UnknownName).findFirst()
            if (unknown == null) {
                unknown = Album(context.getNewAlbumId(), UnknownName, Artist.getUnknown(context))
                unknown = realm.execute { realm.copyToRealm(unknown) }
            }
            return unknown.id
        }
    }
}
```
```kotlin
public RealmClass open class Artist(
        public PrimaryKey open var id: Int = 0,
        public Index open var name: String = "") : RealmObject() {
    companion object {
        public val FieldName: String = "name"
        private val UnknownName: String = "Unknown"
        public platformStatic fun getUnknown(context: Context): Int {
            val realm = Realm.getInstance(context)
            var unknown = realm.where(javaClass<Artist>()).equalTo(FieldName, UnknownName).findFirst()
            if (unknown == null) {
                unknown = Artist(context.getNewArtistId(), UnknownName)
                unknown = realm.execute {
                    realm.copyToRealm(unknown)
                }
            }
            return unknown.id
        }
    }
}
```
```kotlin
public RealmClass open class History(
        public open PrimaryKey var time: Long = -1,
        public open Index var song: Song = Song("", 0, 0),
        public open var listeningDuration: Int = -1) : RealmObject()
```
```kotlin
public RealmClass open class Song(
        public PrimaryKey open var name: String = "",
        public open var artist: Int = 0,
        public open var album: Int = 0,
        public open var duration: Int = 0
) : RealmObject() {
    companion object {
        public val FieldName: String = "name"
    }
}
```

**Comment by cmelchior** [comment]
Have you added ```kapt``` to your your ```build.gradle```? https://github.com/realm/realm-java/pull/1171#issuecomment-108295753

**Comment by yoavst** [comment]
It should be written in your docs under - Do you support Kotlin?
Thank you very much!

**Comment by cmelchior** [comment]
Great you got it working, but yes, we should probably document the setup.

**Comment by yoavst** [comment]
Also please add to the documents that `RealmClass` annotation is needed.

Looks like you add to the database things that should not be added: $kotlinClass, Companion and OBJECT$
![img](http://i.imgur.com/HvuPeSp.png)

**Comment by cmelchior** [comment]
That looks like an error in the Realm Browser and should be fixed there: https://github.com/dmytrodanylyk/realm-browser. We are not adding any special columns for supporting Kotlin.

**Comment by yoavst** [comment]
No, I think realm serialize those fields. Also, I have added Ignore, reinstalled, but it still shows them.
