### ISSUE TITLE
Timeout on Context.finalize()

### ISSUE THREAD

**Issue by HPIWicket** [realm/realm-java#1342]
Hey,

we started seeing following error with the update to Realm 0.82.0:
```
java.util.concurrent.TimeoutException: io.realm.internal.Context.finalize() timed out after 10 seconds
       at java.lang.Object.equals(Object.java:205)
       at java.util.ArrayList.remove(ArrayList.java:418)
       at io.realm.internal.Context.cleanRows(Context.java:69)
       at io.realm.internal.Context.executeDelayedDisposal(Context.java:61)
       at io.realm.internal.Context.finalize(Context.java:113)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:209)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:192)
       at java.lang.Thread.run(Thread.java:818)
```
We also see some longer access times to the Realm after we added some "realm.clear(RealmObject.class)" calls.

Is this a known issue or is there a better way to clear a whole table?

**Comment by beeender** [comment]
@HPIWicket Can you share your project with us which can reproduce this issue? to help@realm.io .

**Comment by HPIWicket** [comment]
I cannot do that :/. But I will try to create a project that can reproduce this issue and try to send it to you.

**Comment by emanuelez** [comment]
Thank you! We're looking forward to that

**Comment by TheRishka** [comment]
I've managed to catch such error as well. Can't understand the pattern to reproduce it, but it appears sometimes.
```
java.util.concurrent.TimeoutException: io.realm.internal.SharedGroup.finalize() timed out after 10 seconds
       at io.realm.internal.SharedGroup.nativeClose(SharedGroup.java)
       at io.realm.internal.Context.asyncDisposeSharedGroup(Context.java:90)
       at io.realm.internal.SharedGroup.finalize(SharedGroup.java:183)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by tmeunier** [comment]
Hi,
I was trying to update to 0.82.0 but I get an error of the same kind on intensive usage of a large realm (70k objects).
Two threads are extracting data (statistics) and when one closes the realm this error occurs.

```java
java.util.concurrent.TimeoutException: io.realm.internal.TableQuery.finalize() timed out after 10 seconds
            at io.realm.internal.TableQuery.finalize(TableQuery.java:73)
            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:209)
            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:192)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by emanuelez** [comment]
@tmeunier Are you able to provide a sample project to reproduce the issue?

**Comment by tmeunier** [comment]
@emanuelez Unfortunately, I cannot share my code nor I have the time to make a sample to reproduce.

My guess is that when using multiple threads with heavy queries on a single realm, this error may occur.

**Comment by kneth** [comment]
As #1313 was merged recently, and can be related to this, I would ask you to try a snapshot release (see `README.md` for details). Please let us know if you can reproduce it or not.

**Comment by kneth** [comment]
I have created a unit test (see #1379) to reproduce it. @teotwaki, @HPIWicket please take a look and tell me if your code is similar.

**Comment by tmeunier** [comment]
Hi,

I have tested with the 0.83.0 SNAPSHOT and the problem is still there.  at
io.realm.internal.TableQuery.finalize(TableQuery.java:73)
However I had more trouble to reproduce (had to stress my interface,
creating up to 3 background threads extracting data from the realm).

Thomas Meunier

2015-08-11 13:00 GMT+02:00 Kenneth Geisshirt <notifications@github.com>:

**Comment by kneth** [comment]
@tmeunier Yes, my model class is very simple (just a string field) but I created 1 mio objects just to be sure to stress the finalizer,

**Comment by kneth** [comment]
I have updated the unit test (making it simpler). I get a timeout with 3 threads and 500000 objects but no timeout with 3 threads and 100000 objects.

**Comment by HPIWicket** [comment]
In our case we don't have this many objects, but we potentially use more threads. I could not reproduce it yet in a debugable version, but I will try to collect more information and try the SNAPSHOT.

Thanks for your help :)

**Comment by kneth** [comment]
@tmeunier @HPIWicket We have issued a fix for this. Please try out a snapshot release (see `README.md` for details).

**Comment by fernandodev** [comment]
I've gotten the same error :(

I'm fetching local database with remote database so:
1. For each table I retrieve a revision number from each entry
2. I send for each table a list with each these numbers
3. I receive the `diff` from server
4. I `copyOrUpdate` the `diff`
5. I remove entries marked as to remove
6. I'm getting `io.realm.internal.Context.finalize() timed out after 10 seconds`

> I suppose that it occurs because I have a large number of entries (more than 5k) for each table. 
> Or because I have a complex call (copy or update) followed by complex query (remove all entries that are marked to remove)

I really don't know :(

**Comment by fernandodev** [comment]
Good news!

`SNAPSHOT 0.83.0` probably was fixed it :smile:

**Comment by cre8ivejp** [comment]
This doesn't happen all time, so I can't reproduce it.
I'm getting 1000 crashes a day.
Version:  0.82.1

java.util.concurrent.TimeoutException: io.realm.internal.TableQuery.finalize() timed out after 10 seconds
       at io.realm.internal.TableQuery.finalize(TableQuery.java:73)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
       at java.lang.Thread.run(Thread.java:818)

**Comment by cmelchior** [comment]
Just to update. We had a problem with our CI server so the SNAPSHOT with a fix for this was never uploaded. This has been fixed now, so `0.83.0-SNAPSHOT` now contains a fix for this.

**Comment by fernandodev** [comment]
I'm using `0.83.0-SNAPSHOT` and error still happens :disappointed:

**Comment by cmelchior** [comment]
Make sure to run `./gradlew clean assemble --refresh-dependencies`. Gradle normally caches SNAPSHOT dependencies for 24 hours so you might still be using an earlier version. If it still fails after that, it would be really helpful if you can create a minimum project that reproduces the behaviour.

**Comment by fernandodev** [comment]
@cmelchior Nice! Thank you! (`--refresh-dependencies`) really solved

**Comment by cmelchior** [comment]
Closing as we have no further indication that this should not be solved by the above PR.

**Comment by ubeyou** [comment]
I got the same error & I'm using 0.84.1 snapshot.

java.util.concurrent.TimeoutException: io.realm.internal.TableQuery.finalize() timed out after 10 seconds
	at java.lang.ref.Reference.<init>(Reference.java:142)
	at java.lang.ref.FinalizerReference.<init>(FinalizerReference.java:42)
	at java.lang.ref.FinalizerReference.add(FinalizerReference.java:54)
	at com.android.internal.os.BinderInternal$GcWatcher.<init>(BinderInternal.java:42)
	at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:47)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
	at java.lang.Thread.run(Thread.java:841)

**Comment by beeender** [comment]
@ubeyou Are you using async queries? Is it possible to share you project which can reproduce this issue with us? to help@realm.io 

Thanks a lot!

**Comment by ubeyou** [comment]
I think I did not close the transaction, which caused the issue. The realm size is getting around than 250mb. Maybe it touched the max file size limit.

**Comment by beeender** [comment]
@ubeyou OK! good to know you found the issue!
