### ISSUE TITLE
Realm does not generate model proxy class (android app)

### ISSUE THREAD

**Issue by Sabrak** [realm/realm-java#1420]
I have model class:

package com.app.model;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class Session extends RealmObject {

    @PrimaryKey
    private String mId;

    public String getId() {
        return mId;
    }

    public void setId(String id) {
        mId = id;
    }
}

But build failed,

:app:compileStagingDebugJavaWithJavac
Note: Processing class Session
/Users/user/Projects/testapp/app/src/main/java/com/app/model/Session.java
Error:(11, 19) error: Getter getId is not associated to any field
Note: Creating DefaultRealmModule
Warning:File for type 'io.realm.DefaultRealmModule' created in the last round will not be subject to annotation processing.
Warning:File for type 'io.realm.DefaultRealmModuleMediator' created in the last round will not be subject to annotation processing.
2 warnings

How it fix?
Thanks

OS: OSX 10.10.5
Java:  "1.8.0_60" 
Android Studio: 1.4
Realm: 0.82.1

**Comment by emanuelez** [comment]
Try renaming your field to ´id´. We implemented some heuristic to associate accessors to fields, but we're soon going to use another approach that fix such issues. In the mean time do the rename or let the IDE generate the accessors for you :)

**Comment by Sabrak** [comment]
Hm.

I renamed the field, but problem still here)

 @PrimaryKey
    private String mName;

    public String getName() {
        return mName;
    }

    public void setName(String name) {
        mName = name;
    }

Error:(11, 19) error: Getter getName is not associated to any field
Note: Creating DefaultRealmModule
Warning:File for type 'io.realm.DefaultRealmModule' created in the last round will not be subject to annotation processing.
Warning:File for type 'io.realm.DefaultRealmModuleMediator' created in the last round will not be subject to annotation processing.

**Comment by Sabrak** [comment]
Thanks, fixed.
