### ISSUE TITLE
couldn't find "librealm-jni.so"

### ISSUE THREAD

**Issue by DenisBronx** [realm/realm-java#1421]
After the last android updates i found this error in every project i use realm

this is the stacktrace:

08-25 16:03:40.457  16017-16017/it.fortech.fortechmobilepayment E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: it.fortech.fortechmobilepayment, PID: 16017
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/it.fortech.fortechmobilepayment-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "librealm-jni.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:114)
            at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:35)
            at io.realm.Realm.<init>(Realm.java:205)
            at io.realm.Realm.createAndValidate(Realm.java:594)
            at io.realm.Realm.create(Realm.java:564)
            at io.realm.Realm.getInstance(Realm.java:411)
            at io.realm.Realm.getInstance(Realm.java:368)
            at io.realm.Realm.getInstance(Realm.java:349)
            at it.fortech.fortechmobilepayment.account.LoginActivity.onCreate(LoginActivity.java:55)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Tested on Nexus 5 device
Android Studio 1.3 
OS X 10.10.5

**Comment by beeender** [comment]
@DenisBronx Can you get into the `/data/data/<package_name>/lib` to see if the `librealm-jni.so` is there?

**Comment by DenisBronx** [comment]
<img width="812" alt="schermata 2015-08-25 alle 16 45 25" src="https://cloud.githubusercontent.com/assets/10074238/9469708/d8dfa798-4b48-11e5-9beb-4f7b62e45b56.png">

yes, and i get the same error in the emulator (i don't know the file explorer very well but i assume the lib folder is empty)

**Comment by beeender** [comment]
@DenisBronx It is a symbolic link point to the anther directory. Please help to check if `/data/app-lib/it.fortech.fotechmobilepayment` contains the `librealm-jni.so` . That directory should have sub directories like `x86` `arm` etc.

**Comment by DenisBronx** [comment]
@beeender it is empty i believe
<img width="826" alt="schermata 2015-08-25 alle 16 55 41" src="https://cloud.githubusercontent.com/assets/10074238/9470016/372edc6e-4b4a-11e5-8499-16128dd42226.png">

**Comment by luca992** [comment]
any updates?

**Comment by joey-harward** [comment]
I think I'm having the same problems.  Did you find a solution?

**Comment by luca992** [comment]
Finally figured out my issue like 5 hours later.... -_-
make sure your gradle version is not:
        classpath 'com.android.tools.build:gradle:+'
I changed mine to the latest and it works like before
        classpath 'com.android.tools.build:gradle:1.3.1'

**Comment by DenisBronx** [comment]
thanks @luca992, it works!

**Comment by beeender** [comment]
It is quite strange since we don't depend on any version of gradle or the android plugin…
Anyway, it is good to see that this problem is solved!
I am closing this issue now, thanks for the feedback!

**Comment by FishOSU** [comment]
Both my coworker and I are seeing this independently and changing the gradle version did not help.

**Comment by joey-harward** [comment]
thanks @luca992, I actually had to set my gradle version to 1.3.0 for it work

**Comment by chrisjenx** [comment]
Has this been reported to b.android.com, this seems to be a build issue with build tools 1.4.0-beta.

**Comment by windzie** [comment]
This same. build issue with build tools 1.4.0-beta

**Comment by hohnamkung** [comment]
This problem still happen in build tools 1.4.0-beta2. Is there a any progress?

**Comment by lvialle** [comment]
I left a bug report on the Android Developer Tools Google+ Community as I had the same issue:
https://plus.google.com/+LudovicVialle/posts/7BRvbb3uKCY

I tried the Jar, same issue, the .so are not copied for any ABI. I think this is an issue within the latest build tools and Gradle.

**Comment by cmelchior** [comment]
Reopening this just so it is more visible, in case anyone else run into this problem. However it doesn't sound like it is something we can do much about at this time unfortunately.

This bug report on the bug tracker https://code.google.com/p/android/issues/detail?id=182061 seems to indicate it is fixed but not yet released for some reason.

**Comment by shadow7** [comment]
I have a similar error message:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shareyourproxy-1/base.apk"],nativeLibraryDirectories=[/data/app/com.shareyourproxy-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "librealm-jni.so"

Like the error says, "lib/arm/librealm-jni.so" is missing from the compiled dependencies. I've tried downloading the realm-0.82.2.jar on the website to use as a local copy. I've extracted the contents of the jar and copied the contents of "lib/armeabi/librealm-jni.so" into the previously mentioned folder hierarchy to attempt to mitigate the error. When I repackage the jar, I can't use it to import any io.realm packages in my java like I could with the original unmodified jar.

I'm using:
Android Studio 1.4 RC-2
buildToolsVersion '23.0.1'  
'com.android.tools.build:gradle:1.3.2' <-- I've tried many versions explicitly

**Comment by kranthipamarthi** [comment]
Had the same issue, used 'com.android.tools.build:gradle:1.2.3' to resolve.

And my app was using latest google+ integration (version 8.1.0) and I had to revert to older version of google+ library to resolve the issue.

**Comment by lvialle** [comment]
1.4.0-beta3 gradle plugin should fix it based on the release notes:
https://sites.google.com/a/android.com/tools/tech-docs/new-build-system#release-notes

I did not tested yet.

**Comment by kevinvanmierlo** [comment]
@lvialle No it isn't fixed yet, unfortunately. I just tried it like an hour ago.

**Comment by jonfry22** [comment]
@lvialle Yeah still not fixed for me either on 1.4.0-beta3 :)

**Comment by tajchert** [comment]
Same here with 1.4.0-beta3, dang can't use onProvideAssistContent() without it.

**Comment by tbsandee** [comment]
Same on 1.4.0-beta4. It's a shame, the 1.4.0 plugin fixes a a showstoppper bug in another area for us. It's like whack-a-mole with this stuff. :/

**Comment by balachandarlinks** [comment]
This is really an annoying show stopper for my app :( Not fixed in 1.4.0-beta4 as well !

**Comment by cmelchior** [comment]
Some more info is here: https://plus.google.com/u/0/+XavierDucrohet/posts/brM78vhMXwj
and the bug report is here: https://code.google.com/p/android/issues/detail?id=188237

**Comment by azizj1** [comment]
beta6 doesn't work either :|

**Comment by azizj1** [comment]
For me the problem wasn't the com.android.tools.build:gradle:1.3.0 or 1.3.1, it was 
classpath 'com.google.gms:google-services:1.4.0-beta3' !
So my project gradle looks like this:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.google.gms:google-services:1.3.0-beta1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

Didn't have to change com.google.android.gms:play-services-plus. Mine is still at com.google.android.gms:play-services-plus:8.1.0

Furthermore, I'm having bunch of issues with com.google.gms:google-services:1.4.0-beta3 - every now and then i'll get this error:

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.transform.api.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

and the building and running of app is super slow.

But anyways, I digress. I solved my issue by replacing
        classpath 'com.google.gms:google-services:1.4.0-beta3'

with 
        classpath 'com.google.gms:google-services:1.3.0-beta1'

Tested on both 4.4.2 and 5.0.2 (physical devices)

**Comment by yshrsmz** [comment]
In my case,

`classpath 'com.android.databinding:dataBinder:1.0-rc3`

caused the problem.
Reverting to rc2 solved the issue.

**Comment by zaki50** [comment]
@yshrsmz I confirmed that.

**Comment by shubhamsizzles** [comment]
Okay, rolling back to `classpath 'com.android.databinding:dataBinder:1.0-rc2` does solve the issue but it seems to break the data binding library itself on gradle `1.4.0-6beta` (which is needed for vector drawables 😔). Its so frustrating.

**Comment by dalinaum** [comment]
@zaki50 Do you know why `dataBinder:1.0-rc3` causes `couldn't find "librealm-jni.so"`? It's a very interesting.

**Comment by zaki50** [comment]
@dalinaum dataBinder:1.0-rc3 replaces com.android.tools.build:gradle plugin with version 1.4.0-beta5, and com.android.tools.build:gradle 1.4.0-beta3 or newer has a bug which does not include .so files into apk file.

**Comment by dalinaum** [comment]
@zaki50 Thanks for your kind explanation :)

**Comment by Chris59160** [comment]
THe bug is still there with com.google.gms:google-services:1.4.0-beta3 . Trying to use google analytics, I have to put com.google.gms:google-services:1.3.1 to make sure Realm can be instantiated

**Comment by emanuelez** [comment]
To anybody experiencing this issue I suggest to start this bug at Google in order to gain visibility and priority: https://code.google.com/p/android/issues/detail?id=188237

**Comment by yusukeokui** [comment]
I use this and solved!
classpath 'com.google.gms:google-services:1.3.0-beta1'

@emanuelez thank you!

**Comment by Saketme** [comment]
I neither have the data-binding library nor the GMS library and yet I am seeing this error. It's highly frustrating. Here's what my build.gradle file looks like: https://gist.github.com/e9828334c69c22b86e24

Can anybody please help me find the error source?

**Comment by kneth** [comment]
@Saketme The bug in the Android Gradle plugin hasn't been fixed yet but we all hope it will be soon (at least before it leaves the beta state). For the time being, version 1.3 is your best option.

**Comment by Saketme** [comment]
Oh okay, thanks

**Comment by hohnamkung** [comment]
Finally fixed in 1.5.0-beta1 (2015/11/02)

**Comment by cmelchior** [comment]
Great to hear. The issue on the bug tracker hasn't been update yet though, so we will keep this open a bit longer until it is confirmed there.

**Comment by GiorgosOikonomou** [comment]
Update to gradle 1.5.0-beta1 and the problem with the librealm-jni.so is fixed

classpath 'com.android.tools.build:gradle:1.5.0-beta1'

**Comment by kneth** [comment]
@GiorgosOikonomou Thanks for reporting it.

**Comment by intrications** [comment]
The final 1.5.0 build tools release fixes this for me.

**Comment by kneth** [comment]
@intrications Thanks for the update!

**Comment by kneth** [comment]
I have tested with android gradle plugin 1.5.0, databinder 1.0-rc4 and Realm 0.84.2 and I don't see issue with loading `.so` files. I will close the issue. If you experience the issue, don't hesitate to either reopen or create a new issue.

**Comment by marcelohd** [comment]
Look This
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/project/files/studio-fd/dex/slice-main-classes.dex", dex file 
"/data/data/project/files/studio-fd/dex/main-classes.dex"],nativeLibraryDirectories=
[/data/data/project/files/studio-fd/lib, /vendor/lib64, /system/lib64]]] couldn't find "librealm-jni.so"

Using Android Studio 2.0 Preview 9  Gradle 2.0.0-alpha9'

**Comment by cmelchior** [comment]
Hi @marcelohd Are you using Instant Run? Try to do a clean rebuild and see if that fixes it.

**Comment by marcelohd** [comment]
Ok , I will do

**Comment by marcelohd** [comment]
Realm and instant run not combine

**Comment by cmelchior** [comment]
Instant Run is still very much a preview feature and Realm just uses Annotation processing like a lot of other libraries out there. I am afraid there is not much we can do about Googles bugs expect hoping they get fixed. If you can reproduce the error I would encourage you to create a bug report on https://code.google.com/p/android/issues/entry?template=Android%20Studio%20Instant%20Run%20Bug

**Comment by kneth** [comment]
We should definitely add it to our documentation that Realm and instant runs don't combine well.

**Comment by cmelchior** [comment]
We are not incompatible as such, e.g I have Instant Run working. , but Instant Run does _a lot_ under the hoods and is still in alpha stage, so there might be corner cases where it breaks.

**Comment by yong076** [comment]
Yah, I got a Same Issue..
2.0.0 - beta2
gradle version 2.10

**Comment by marcelohd** [comment]
while Google not solve this, can Clean and Rebuild it´s this works.

**Comment by kneth** [comment]
@marcelohd Thanks for sharing.

**Comment by kouroshfar** [comment]
i got a same issue and not solved yet. Did you find a solution?

**Comment by marcelohd** [comment]
The recomemnd Google is disable instant run, but it´s not solved the solution is ever clean and build

**Comment by kevinvanmierlo** [comment]
@marcelohd  Disabling instant run doesn't fully work a few methods from instant run are still being called (I filed a crash report [here](https://code.google.com/p/android/issues/detail?id=200115) which has something to do with this). The best thing you can do is revert to gradle 1.5.0 or disabling Java Incremental compilation (it says the newest gradle plugin version already does that automatically, but it doesn't on my project). To disable Java Incremental compilation you add `android.incrementalJavaCompile=false` to the gradle.properties file.

**Comment by kouroshfar** [comment]
I'm using android studio 1.5.1 and don't use version 2. actually i don't have instant run.
I use gradle version 1.5.0 and Realm 0.87.4, but not fixed yet :|

**Comment by kouroshfar** [comment]
I have tested with android studio 2.0 beta 4,  android gradle plugin 2.0.0-beta4, and Realm 0.87.4 and I see the same issue with loading .so files. :/

**Comment by marcelohd** [comment]
without instant run?

**Comment by kouroshfar** [comment]
@marcelohd Yes. When i disabled instant run, then throw old exception (couldn't find "librealm-jni.so")!

**Comment by dalinaum** [comment]
Hello @kouroshfar What devices did you test on? Can you reproduce this problem?

**Comment by kouroshfar** [comment]
Hello @dalinaum . I'm using Sony Z3 for debug. I'm testing my test app on genymotion, but reproduce this problem and not solved.

**Comment by cmelchior** [comment]
Hi @kouroshfar 
Sorry for the late reply. Note that you need to uninstall the old app even after disabling Instant Run, as the byte code might still be wrong on the device. Are you still seeing this problem then?

**Comment by marcelohd** [comment]
Hi @cmelchior,
I will check, possible can happen in my code too

**Comment by shalperin** [comment]
couldn't find "librealm-jni.so"
Build tools com.android.tools.build:gradle:2.0.0-beta6 (android studio 2)
"resolved" by disabling instant run.

**Comment by Queatz** [comment]
Got around it by disabling Instant Run.

**Comment by cmelchior** [comment]
Hi @kouroshfar 
Google introduced some fixes to this problem in beta6 (Realm uses native code): http://tools.android.com/recent/androidstudio20beta6availableinthecanarychannel

I'll close this issue now, but feel free to reopen if you see this on beta6 or above.

**Comment by hardysim** [comment]
Hey, I have the same problem with Android Studio 2.0 Beta 6. Only disabling InstantRun is working.

**Comment by Queatz** [comment]
beta6 not working for me either, still need to disabled Instant Run.

**Comment by marcelohd** [comment]
Any version starting Android Studio 2.0 (Preview), only build with instant run disable.

**Comment by cmelchior** [comment]
Apparently the fix got pushed to beta7 instead: https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=200635

**Comment by kneth** [comment]
Let's close it as it is scheduled but out of our hands.

**Comment by Botasky369** [comment]
I got the same issue, I'm trying to update the Realm from 0.87 to 2.0.0 , but i can't run the app with the problem com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/librealm-jni.so;
And my gradle version is 'com.android.tools.build:gradle:2.2.0'.  I also try to disbinding the instant run and add classpath 'com.google.gms:google-services:1.3.0-beta1' in Gradle, but it doesn't work too.

**Comment by beeender** [comment]
@Botasky369 Do you have any other library which has a `.so` file? We removed `armeabi` so in 2.0.0 which will cause this problem if your other library has an `armeabi` so file.

**Comment by Botasky369** [comment]
@beeender Yes,  I found some .so in my /data/data/packagename/lib file, some like libamapv304.so/libamapv304ex.so/libBugTags.so and others . But there is not librealm-jni.so.
So you mean that we have to delete the armeabi file in our project?

**Comment by beeender** [comment]
@Botasky369 It depends. If all the libs have `armeabi-v7a` so files, you can safely exclude those `armeabi` version since all arm devices in the market today should support  `armeabi-v7a` well.

**Comment by Botasky369** [comment]
@beeender I delete the `armabi` file in my project, But it also doesn't work.

**Comment by Botasky369** [comment]
@beeender I have clean and rebulid the projiect.

**Comment by beeender** [comment]
@Botasky369 can you decompress you final apk file, and show the list and structure of `lib` dir inside the apk?

**Comment by Botasky369** [comment]
@beeender Well, I found there has some code was suspicious at the gradle, and I delete it, and the app can run normal.Thx.
The code delete:
![image](https://cloud.githubusercontent.com/assets/13627665/18983765/6327c470-8721-11e6-8a01-759da790a4ff.png)
Thank again. You can close my isssue.

**Comment by rahulkumarit** [comment]
compile 'io.realm:realm-android:0.87.4'
I have added but getting in error in run time..

**Comment by Zhuinden** [comment]
Hello, 0.87.4 is super old, the latest version is 4.3.4 

please read https://realm.io/docs/java/latest/

**Comment by rhonyabdullah** [comment]
Hello, this is appear again if i'm using proguard on my release buildTypes:
```
java.lang.RuntimeException: Unable to create application com.myapps.android.app.Myapps: com.getkeepsafe.relinker.MissingLibraryException: lib/x86/librealm-jni.so
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: lib/x86/librealm-jni.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(SourceFile:85)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(SourceFile:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(SourceFile:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:57)
        at io.realm.internal.RealmCore.a(SourceFile:60)
        at io.realm.Realm.a(SourceFile:258)
        at com.myapps.android.app.Myapps.initRealm(SourceFile:102)
        at com.myapps.android.app.Myapps.onCreate(SourceFile:82)
```

**Comment by Zhuinden** [comment]
Well if Relinker can't find it, it's not there. You might have an abiFilter set up and it removes `x86`.

**Comment by rhonyabdullah** [comment]
So what should i do ? Is this correct if i'm doing this:
```
android {
packagingOptions {
        exclude 'lib/x86_64/librealm-jni.so'
    }
}
```

**Comment by Zhuinden** [comment]
Do you have any other native libraries that are 32-bit only?

**Comment by rhonyabdullah** [comment]
No, i don't have.
