### ISSUE TITLE
DynamicRealmObject setObject() does not check types properly

### ISSUE THREAD

**Issue by rogerso** [realm/realm-java#1451]
In `DynamicRealmObject`'s `setObject(String fieldName, DynamicRealmObject value)`, the type of the parameter should be compared against the field's defined type. Instead, it is being compared against the type of the object itself.

The offending lines are in DynamicRealmObject.java lines 404-409.

**Comment by cmelchior** [comment]
Ups, you are right. That is embarrassing. Thanks for reporting this.

**Comment by cmelchior** [comment]
This has been fixed in the new Dynamic API that was just merged to master: https://github.com/realm/realm-java/pull/1496

**Comment by rogerso** [comment]
Looks like this issue still exists... pull request incoming.

**Comment by cmelchior** [comment]
@rogerso Thanks

**Comment by cmelchior** [comment]
A fix has been merged to master and will be part of `0.86.1`
