### ISSUE TITLE
Couldn't load realm-jni (io.realm.internal.RealmCore.loadLibrary) 0.82.2

### ISSUE THREAD

**Issue by datrixo** [realm/realm-java#1534]
Hi!

Our crash analytic tool reported problems with loading realm-jni for version 0.82.2 (and previous also). Unfortunetly most of our crashes comes from realm.io library. We don't have any more accurate data for this bug.

RealmCore.java line 114
io.realm.internal.RealmCore.loadLibrary

java.lang.ExceptionInInitializerError
       at io.realm.Realm.(Realm.java:205)
       at io.realm.Realm.createAndValidate(Realm.java:594)
       at io.realm.Realm.create(Realm.java:564)
       at io.realm.Realm.getInstance(Realm.java:537)...

Caused by: java.lang.UnsatisfiedLinkError: Couldn't load realm-jni: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:365)
       at java.lang.System.loadLibrary(System.java:535)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:114)
       at io.realm.internal.SharedGroup.(SharedGroup.java:35)
       at io.realm.Realm.(Realm.java:205)
       at io.realm.Realm.createAndValidate(Realm.java:594)
       at io.realm.Realm.create(Realm.java:564)
       at io.realm.Realm.getInstance(Realm.java:537)

**Comment by emanuelez** [comment]
Is there a pattern about which devices this happens on?

**Comment by datrixo** [comment]
For example in last 7 days we hah 101 crashes for 3 users:
1) System versions: 4.1.2, 4.4.2, 4.4.4
2) Smartphones: 
   Samsung: GT I9305T, GT I9192
   Sony: D2212

**Comment by dalinaum** [comment]
It seems a similar issue with #1527.

I don't think it is not hardware issues. But draw up a list of models which are reported.

* Samsung GT I9300, I9305T: Galaxy S3
* Samsung GT I9500: Galaxy S4
* Samsung GT I9192: Galaxy S4 mini
* Samsung GT I9082: Galaxy Grand
* Sony D2212: Xperia E3 Dual
* TECNO Y4
* Cherry X170

**Comment by renjupaul** [comment]
same here. any hacks? tried with 'com.android.tools.build:gradle:1.3.2' and all latest versions, but no luck.

**Comment by datrixo** [comment]
In my opinion this should be **critical bug**. We using realm.io on large scale and these crashes have influence on our app reviews...

**Comment by emanuelez** [comment]
All bugs are critical to us. Are you using realm in conjunction with some other libraries that rely on native code?

**Comment by datrixo** [comment]
For full info let me list all of libs which we are using in app for release builds:
- com.jakewharton:butterknife
- de.greenrobot:eventbus (2.4)
- org.threeten:threetenbp
- com.path:android-priority-jobqueue
- com.facebook.android:facebook-android-sdk
- io.segment.analytics.android:flurry
- com.viewpagerindicator:library:2.4.1@aar
- com.crashlytics.sdk.android:crashlytics:2.5.1@aar
- com.parse.bolts:bolts-android
- Parse
- com.google.dagger:dagger:2.1

and ofc some libs from android.support.

**Comment by emanuelez** [comment]
Would it be possible for you to unzip your APK file, cd into the lib folder and run the `tree` command? Such command is built-in on Windows but you might need to install it if you run on Mac or Linux. I basically want to see if all the .so files are in all the ABI folders.

**Comment by datrixo** [comment]
From production .apk:

├───arm64-v8a
│       librealm-jni.so
│
├───armeabi
│       librealm-jni.so
│
├───armeabi-v7a
│       librealm-jni.so
│
├───mips
│       librealm-jni.so
│
└───x86
        librealm-jni.so

**Comment by kneth** [comment]
@datrixo Do you see other `.so` files (non Realm ones) in the output of `tree`?

**Comment by datrixo** [comment]
No. It's all. Nothing else.

**Comment by kneth** [comment]
Then, it is very strange indeed.The `.so` is loaded when you first get a Realm instance.

Did you enable NDK support for Crashlytics?

**Comment by datrixo** [comment]
Nope, NDK support for Crashlytics is disabled. I will upload today to market version with enabled NDK support but I think it won't change anything because it works only when you are compiling by yourself ndk libs.

**Comment by kneth** [comment]
@datrixo I was actually more concerned if enabling NDK support might cause problems if Crashlytics doesn't support the same architectures as Realm does.

**Comment by beeender** [comment]
@datrixo We updated the doc about the native so file issue here https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

Could you please let us know if it helps?

**Comment by datrixo** [comment]
Great to have more informations about that but in our case this soultion will not help - we dont have any other native libraries, only realm.

**Comment by kneth** [comment]
We have merged #1771 to use ReLinker to give the loading of `.so` files a second chance to work. You can try it out as a snapshot release.

**Comment by OAbdan** [comment]
any updates on this issue i'm still seeing it on crashlytics?

**Comment by kneth** [comment]
@OAbdan Can you provide us with an example on how it crashes? We might not have covered all cases in #1771.

**Comment by OAbdan** [comment]
@kneth the crash never happened to me. just showing up on Fabric

**Comment by kneth** [comment]
@OAbdan Can you show us the log? And you are using version 0.88.1 or later, right?

**Comment by hmedat2008** [comment]
@kneth 

Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load realm-jni from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.opensooq.OpenSooq-1.apk,libraryPath=/data/app-lib/com.opensooq.OpenSooq-1]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:355)
       at java.lang.System.loadLibrary(System.java:525)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:117)
       at io.realm.internal.SharedGroup.(SharedGroup.java:42)
       at io.realm.internal.SharedGroupManager.(SharedGroupManager.java:43)
       at io.realm.BaseRealm.(BaseRealm.java:76)
       at io.realm.Realm.(Realm.java:126)
       at io.realm.Realm.createAndValidate(Realm.java:246)
       at io.realm.Realm.createInstance(Realm.java:231)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:197)
       at com.opensooq.OpenSooq.util.RealmWrapper.getChatRealm(RealmWrapper.java:67)
       at com.opensooq.OpenSooq.util.RealmWrapper.getUnreadMessages(RealmWrapper.java:685)
       at com.opensooq.OpenSooq.ui.home.HomeActivity.updateChatNotificationsCounter(HomeActivity.java:337)
       at com.opensooq.OpenSooq.ui.home.HomeActivity.onStart(HomeActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
       at android.app.Activity.performStart(Activity.java:5379)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2276)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
       at android.app.ActivityThread.access$700(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5450)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by beeender** [comment]
@hmedat2008 Please check this https://github.com/realm/realm-java/issues/3175#issuecomment-232214905 to see if it helps

**Comment by hmedat2008** [comment]
@kneth 

Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load realm-jni from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.x.x-1.apk,libraryPath=/data/app-lib/com.x.x-1]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:355)
       at java.lang.System.loadLibrary(System.java:525)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:117)
       at io.realm.internal.SharedGroup.(SharedGroup.java:42)
       at io.realm.internal.SharedGroupManager.(SharedGroupManager.java:43)
       at io.realm.BaseRealm.(BaseRealm.java:76)
       at io.realm.Realm.(Realm.java:126)
       at io.realm.Realm.createAndValidate(Realm.java:246)
       at io.realm.Realm.createInstance(Realm.java:231)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:197)
       at com.x.x.util.RealmWrapper.getChatRealm(RealmWrapper.java:67)
       at com.x.x.util.RealmWrapper.getUnreadMessages(RealmWrapper.java:685)
       at com.x.x.ui.home.HomeActivity.updateChatNotificationsCounter(HomeActivity.java:337)
       at com.x.x.ui.home.HomeActivity.onStart(HomeActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
       at android.app.Activity.performStart(Activity.java:5379)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2276)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
       at android.app.ActivityThread.access$700(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5450)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
       at dalvik.system.NativeStart.main(NativeStart.java)

I replaced my package name with com.x.x

**Comment by kneth** [comment]
@hmedat2008 Which version of Realm do you use? And do you include other `.so` files in your app?
