### ISSUE TITLE
BadVersionException

### ISSUE THREAD

**Issue by Kistamushken** [realm/realm-java#2021]
Hey, guys. I keep getting this exception. I am using 0.87.1 version of Realm(and I use Realm as a singleton).  

My situation looks like this: there is navigation button which starts a fragment, which makes an async query for objects in onStart() method. This exception rises when user spams this navigation button or just makes fast transactions between fragments.

```java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1262
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1491)
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1467)
E/AndroidRuntime:     at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime:  Caused by: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1262
E/AndroidRuntime:     at io.realm.internal.TableQuery.nativeFindAllSortedWithHandover(Native Method)
E/AndroidRuntime:     at io.realm.internal.TableQuery.findAllSortedWithHandover(TableQuery.java:490)
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1480)
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1467) 
E/AndroidRuntime:     at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36) 
E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)```

By the way, sometimes my during fast transactions between fragments my app crashes with SIGSEV  or just completely freezes without throwing ANR, dunno if it's connected to the BadVersion, but just in case.

**Comment by dalinaum** [comment]
Hello, @Kistamushken

If the the specific version of the async query is not equal to the read lock's version, you can encounter `BadVersionException`. Is there `removeChangeListener()` or `removeChangeListeners()` in `onStop()` method? I think it has relevance to your problem.

**Comment by Kistamushken** [comment]
@dalinaum Yeah, I do have removeChangeListener() in the onStop() method, I also tried removeChangeListener(listener) but it didn't really helped. Btw, can It be relative to the SIGSEV I get from time to time, I mean this thing with RealmChangeListener?

**Comment by nhachicha** [comment]
seems related to #2027

**Comment by cmelchior** [comment]
We have discovered a bug in how we handle queries across threads. This is currently being fixed by: https://github.com/realm/realm-core/pull/1450

**Comment by cmelchior** [comment]
We have just released 0.87.4 with a potential fix for this. We still haven't been able to reproduce the exact error you are reporting here, but upon investigation found something that appeared to be the root cause. So if you can test with 0.87.4 that would be much appreciated.

**Comment by cmelchior** [comment]
Seems fixed according to #2027

**Comment by fuwaneko** [comment]
I have similar error on version 0.87.4:
```
java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1094
at io.realm.RealmQuery$5.call(RealmQuery.java:1847)
at io.realm.RealmQuery$5.call(RealmQuery.java:1817)
at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

Caused by: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1094
at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:438)
at io.realm.RealmQuery$5.call(RealmQuery.java:1829)
at io.realm.RealmQuery$5.call(RealmQuery.java:1817) 
at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:818) 
```
Occurs randomly on app launch when it performs background network operations with writing results to Realm. On foreground activity I have listeners to Realm updates.

**Comment by hohnamkung** [comment]
I'm using Realm v0.87.4 and have a similar crash. 

    Fatal Exception: java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1274
       at io.realm.RealmQuery$4.call(RealmQuery.java:1667)
       at io.realm.RealmQuery$4.call(RealmQuery.java:1642)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
    Caused by io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1274
       at io.realm.internal.TableQuery.nativeFindAllMultiSortedWithHandover(TableQuery.java)
       at io.realm.internal.TableQuery.findAllMultiSortedWithHandover(TableQuery.java:498)
       at io.realm.RealmQuery$4.call(RealmQuery.java:1655)
       at io.realm.RealmQuery$4.call(RealmQuery.java:1642)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Comment by heitorpr** [comment]
Hey, im having this issue too. Im using realm: 0.87.5. And this is the stacktrace that fabric got to me.

[Crashlytics - Crash - Bad Version](http://crashes.to/s/9264bbf4635)

**Comment by hohnamkung** [comment]
I'm using Realm v0.87.5, this exception still happening with same stack trace.

**Comment by heitorpr** [comment]
Any tip to not break the app if this issue happen? like a try catch or something...

**Comment by cmelchior** [comment]
Hi @heitorpr Unfortunately not. Right now the only work-around is using `findAll` instead of `findAllAsync`. A fix is being merged as we speak however: #2397

**Comment by heitorpr** [comment]
I see... Thanks =).

**Comment by hohnamkung** [comment]
Hi Realm team.
We've updated Realm v0.88.0 and still have a `BadVersionException` problem.

Exception log from fabric is a little different from v0.87.5.
I attached it for your information.

    Fatal Exception: java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1274
       at io.realm.RealmQuery$4.call(RealmQuery.java:1667)
       at io.realm.RealmQuery$4.call(RealmQuery.java:1642)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
    Caused by io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1274
       at io.realm.internal.TableQuery.nativeFindAllMultiSortedWithHandover(TableQuery.java)
       at io.realm.internal.TableQuery.findAllMultiSortedWithHandover(TableQuery.java:498)
       at io.realm.RealmQuery$4.call(RealmQuery.java:1655)
       at io.realm.RealmQuery$4.call(RealmQuery.java:1642)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by cmelchior** [comment]
Hi @hohnamkung 
Yes, sorry for the trouble. We have finally been able to reproduce this and located the root cause. We hope to have a fix in 0.88.1: https://github.com/realm/realm-java/pull/2426

**Comment by hohnamkung** [comment]
Wow. I'm really looking forward to v0.88.1.
Could you tell me when v0.88.1 is expected to be released?
This exception is quite urgent for us. Nearly 1K ~ 2K users have this exception **in everyday**.

**Comment by cmelchior** [comment]
We plan to release it today

**Comment by heitorpr** [comment]
:D. Thx!!! Looking foward to this!! :D
Em 14 de mar de 2016 7:51 AM, "Christian Melchior" <notifications@github.com>
escreveu:

**Comment by cmelchior** [comment]
@hohnamkung @heitorpr 
Due to the complexity of this, it unfortunately won't make it into 0.88.1 after all, but there will be a 0.88.2 within the next couple of days with a fix for this. Sorry for the trouble this is causing.

**Comment by heitorpr** [comment]
Ook! Thx!
Em 14 de mar de 2016 10:16 AM, "Christian Melchior" <
notifications@github.com> escreveu:

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:36590 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmN4-001xjV-LH
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:38:38 -0400
Date: Mon, 14 Mar 2016 03:00:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457949651;
	bh=SGDoPfuoWTjw13hN6Lm7By/wF/9qHu+CoXBfAzWd/mY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=EZ8dC/heIByVlyk3UL+GTxBargtZuCVt4b+dYk3KrPn4WViPN7fQLNpKhpHbpudvF
	 wYrzDscrT7ltlG/Q97uaD6l/erQV4rweX3rPIIIoXDZtq66Q545nebBqLRfmQR/p3m
	 4hGCopTDYC60F7LzuMousLyOJnUgUvm7vsmV+KGI=

**Comment by cmelchior** [comment]
@heitorpr @hohnamkung 0.88.2 has been released with a fix for this.

**Comment by heitorpr** [comment]
=D. Thank you!!!!

2016-03-15 16:59 GMT-03:00 Christian Melchior <notifications@github.com>:

**Comment by dbacinski** [comment]
Problem still occurs in version 0.88.3 on low end devices like LG L4 E440

> 04-18 09:42:34.133: E/AndroidRuntime(10716): FATAL EXCEPTION: main
04-18 09:42:34.133: E/AndroidRuntime(10716): java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1099
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at io.realm.RealmQuery$5.call(RealmQuery.java:1974)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at io.realm.RealmQuery$5.call(RealmQuery.java:1944)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at java.lang.Thread.run(Thread.java:856)
04-18 09:42:34.133: E/AndroidRuntime(10716): Caused by: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1099
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:443)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	at io.realm.RealmQuery$5.call(RealmQuery.java:1956)
04-18 09:42:34.133: E/AndroidRuntime(10716): 	... 7 more

**Comment by cmelchior** [comment]
Hi @dbacinski 
Thanks, we will look into it.

**Comment by cmelchior** [comment]
Hi @dbacinski 
We released 0.90 which fixed a few corner cases around this. Is it something you can verify or are you only seeing this crash through Crashlytics or similar?

**Comment by dbacinski** [comment]
We were able to reproduce this issue on our devices. 

There were breaking changes in 0.90, so we need to do some work in order to upgrade. I will let you know when we will retest it.

**Comment by kneth** [comment]
@dbacinski Did you have a chance to upgrade and rerun your tests?

**Comment by emanuelez** [comment]
@dbacinski We haven't heard from you in 9 days so I'm closing this issue. Please let us know if it needs to be reopened!

**Comment by Tomekkk** [comment]
Reproduced on `2.0.2`
Occurs randomly on opening and closing app.
I don't know if it is important but in the app I'm using findAllAsync()/findFirstAsync() with asObservable() for quering database.


```11-14 12:19:14.507 E: jni: ThrowingException 7, std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1131, .
11-14 12:19:14.526 E: io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1131
                          at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
                          at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:446)
                          at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
                          at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
                          at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                          at java.lang.Thread.run(Thread.java:761)
11-14 12:19:14.583 E: FATAL EXCEPTION: main
                      Process: com.my.app, PID: 1540
                      java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1131
                          at io.realm.AndroidNotifier.throwBackgroundException(AndroidNotifier.java:139)
                          at io.realm.RealmQuery.closeSharedRealmAndSendEventToNotifier(RealmQuery.java:2201)
                          at io.realm.RealmQuery.access$000(RealmQuery.java:62)
                          at io.realm.RealmQuery$5.call(RealmQuery.java:2141)
                          at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
                          at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                          at java.lang.Thread.run(Thread.java:761)
                       Caused by: io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1131
                          at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
                          at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:446)
                          at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
                          at io.realm.RealmQuery$5.call(RealmQuery.java:2115) 
                          at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36) 
                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                          at java.lang.Thread.run(Thread.java:761) ```

**Comment by ppamorim** [comment]
Hi @cmelchior @kneth @emanuelez
Happening on `2.2.2`. This problem appears randomly.
Using Kotlin `1.0.4`, LG G2 @ 6.0.1

```
E: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130, .
E: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
E: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1284, .
E: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1284
E: io.realm.internal.async.BadVersionException: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
       at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
       at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:436)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
D: Shutting down VM
E: FATAL EXCEPTION: main
   Process: com.tpro.dictate, PID: 22079
   Theme: themes:{default=overlay:com.brit.swiftdark, fontPkg:com.brit.swiftdark, com.android.systemui=overlay:com.brit.swiftdark, com.android.systemui.navbar=overlay:com.brit.swiftdark}
   java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
       at io.realm.AndroidNotifier.throwBackgroundException(AndroidNotifier.java:138)
       at io.realm.RealmQuery.closeSharedRealmAndSendEventToNotifier(RealmQuery.java:2201)
       at io.realm.RealmQuery.access$000(RealmQuery.java:62)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2141)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
    Caused by: io.realm.internal.async.BadVersionException: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
       at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
       at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:436)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2115) 
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36) 
       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
       at java.lang.Thread.run(Thread.java:818) 
```

**Comment by Zhuinden** [comment]
@ppamorim when https://github.com/realm/realm-java/pull/3834 is merged, this issue will probably be fixed along with it

**Comment by ppamorim** [comment]
Please, I beg you to do this.

**Comment by Zhuinden** [comment]
@ppamorim in the meantime, I think a possible solution would be to use `findAll` instead of `findAllAsync` and etc. But the pull request I mentioned seems scheduled for 2.4.0.

**Comment by ppamorim** [comment]
@Zhuinden I will be fired :D

**Comment by Zhuinden** [comment]
Okay that's not fun, what is your deadline?

**Comment by Zhuinden** [comment]
But seriously, if you replace all async query method with sync query methods, then this can be fixed temporarily.

**Comment by ppamorim** [comment]
Today, I can't do this change... But I can use a snapshot of the fixed version, what do you think?

**Comment by Zhuinden** [comment]
The object store results integration is not merged yet.

**Comment by ppamorim** [comment]
@Zhuinden Solved?

**Comment by wenmagi** [comment]
Happening on 2.2.2. The problem happened because I use the method of `findFirstAsync` after deleting caches of my app.

`06-13 16:33:44.145 15438-15835/? E/REALM_JAVA: io.realm.internal.async.BadVersionException: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
                                                   at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
                                                   at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:436)
                                                   at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
                                                   at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
                                                   at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                   at java.lang.Thread.run(Thread.java:761)
06-13 16:33:44.170 15438-15468/? E/CrashlyticsCore: Tried to write a fatal exception while no session was open.
06-13 16:33:44.185 15438-15438/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.zhihu.android.alpha, PID: 15438
                                                   java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
                                                       at io.realm.AndroidNotifier.throwBackgroundException(AndroidNotifier.java:138)
                                                       at io.realm.RealmQuery.closeSharedRealmAndSendEventToNotifier(RealmQuery.java:2201)
                                                       at io.realm.RealmQuery.access$000(RealmQuery.java:62)
                                                       at io.realm.RealmQuery$5.call(RealmQuery.java:2141)
                                                       at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
                                                       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: io.realm.internal.async.BadVersionException: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1130
                                                       at io.realm.internal.TableQuery.nativeFindWithHandover(Native Method)
                                                       at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:436)
                                                       at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
                                                       at io.realm.RealmQuery$5.call(RealmQuery.java:2115) 
                                                       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) `

**Comment by beeender** [comment]
@ppamorim @wenmagi We have some fundamental changes for async queries when we introduce the fine grained notifications. This issue should be fixed in the latest version. Please update the Realm to the latest version.

**Comment by Zhuinden** [comment]
Agreed, Realm 2.x notifications with async queries had oddities, Realm 3.1.4 or Realm 3.3.x+ are much better choice

**Comment by stan-ko** [comment]
This issue still happens to my app on user devices
```
Caused by io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 152
       at io.realm.internal.OsResults.nativeSize(OsResults.java)
       at io.realm.internal.OsResults.size + 367(OsResults.java:367)
       at io.realm.OrderedRealmCollectionImpl.size + 341(OrderedRealmCollectionImpl.java:341)
       at io.realm.RealmResults.size + 72(RealmResults.java:72)
       at mypackage.util.UDHelper.getUDs + 84(UDHelper.java:84)
```
UDHelper has following code:
```
		final RealmResults<SDocs> registeredDocs = sMainUIRealmInstance.where(SDocs.class).findAll();
		int registeredDocsCount = registeredDocs.size(); // this is line 84 where crash happens
```
previously it was just check `registeredDocs.isEmpty()` with absolutely the same crash so I tried to use `registeredDocs.size()` but no luck. I realize `isEmpty()` most probably utilizes the same `size()` method.
Realm is declared in `gradle.build ` as `classpath "io.realm:realm-gradle-plugin:5.9.1"`.

**Comment by Zhuinden** [comment]
This generally shouldn't happen, but what happens if you put `refresh()` above it?

**Comment by alexneo2003** [comment]
> This generally shouldn't happen, but what happens if you put `refresh()` above it?

hi. i'm have same issue at isEmpty() and size()
refresh() not helping me)
i'm using realm 6.0.0

```
    io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 152
        at io.realm.internal.OsResults.nativeSize(Native Method)
        at io.realm.internal.OsResults.size(OsResults.java:371)
        at io.realm.OrderedRealmCollectionImpl.size(OrderedRealmCollectionImpl.java:341)
        at io.realm.RealmResults.size(RealmResults.java:68)
```

**Comment by cmelchior** [comment]
@alexneo2003 Is it something you can reproduce?

**Comment by alexneo2003** [comment]
@cmelchior i'm running Espresso test on my corporate app.
at first starting app in background downloading many static data. like schedule of working time, news by company and etc. and all this data writing in realm database.
at first run in test i'm cleaning app data and run it. and it run background operations with downloading/writing data.
at end of first testing app stoped and runing new test with run new app activity. and app create new instances for downloading/writing data.
but background data after first running still in progress and at this place my app is crashed with same error
