### ISSUE TITLE
Gradle: Cannot find Relinker

### ISSUE THREAD

**Issue by mithrann** [realm/realm-java#2415]
Hi,
I am getting error when i try to use 0.88.0 instead of 0.87.5

`Error:Failed to resolve: com.github.KeepSafe:ReLinker:1.1`

**Comment by cmelchior** [comment]
Are you using the new gradle plugin as described here: https://realm.io/news/realm-java-0.88.0/ ?

**Comment by mithrann** [comment]
Yes,  i am using new gradle plugin in my datahandler library of my app
 `buildscript {
 repositories {
    jcenter()
 }
 dependencies {
    classpath 'io.realm:realm-gradle-plugin:0.88.0'
 }
}
apply plugin: 'realm-android'`  and it gives that error.

**Comment by zoonooz** [comment]
@mithrann ran into same problem, quick fix is add these lines in the app build.gradle

```
repositories {
    maven { url 'https://jitpack.io' }
}
```

**Comment by emanuelez** [comment]
That's unexpected since the Realm Gradle plugin should be adding the jitpack repository as you can see here:

https://github.com/realm/realm-java/blob/master/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy#L52

Did you try cleaning your repo? Sometime the Gradle cache interferes with dependencies.

**Comment by jjhesk** [comment]
+1

**Comment by zoonooz** [comment]
@emanuelez I think it's working only in normal android project but not with the library module. As it will compile to AAR without external library inside so the app module have to add the repository again when using it.

**Comment by mithrann** [comment]
Yup, still not working in lib project.

**Comment by zoonooz** [comment]
@mithrann @jjhesk It's working for me in lib project with this setup

**app/build.gradle**
```
buildscript {
    ....
}
repositories {
    maven { url 'https://jitpack.io' }
}
```

**lib/build.gradle**
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:0.88.0"
    }
}
apply plugin: 'com.android.library'
apply plugin: 'realm-android'
```

**Comment by mithrann** [comment]
@zoonooz that is also not working for me.

**Comment by zoonooz** [comment]
:disappointed_relieved:

**Comment by mithrann** [comment]
@cmelchior  any update on the issue?

Thanks.

**Comment by emanuelez** [comment]
A fix has been merged and should soon be available in our SNAPSHOT release.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:38165 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflk2-001g6L-VN
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:18 -0400
Date: Mon, 14 Mar 2016 04:40:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457955627;
	bh=icH9RFMXgD3JZCV5fIjFiUo9qz5nthl53N2rTTHyhc8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=j+e6aSbCbfPwx64DfBa4J2FNYNj89XW9sJSUBG8jYs12LpuY8smvUbAkfwVmBwfw1
	 YMEkwWWLat4DZE0hAGUoRC5Grryg4sTNfMDFXg7hrBGw9LMGAD5MXJjHX/hCN6ALJL
	 5H9Noay1z3i6FE/ih4nNg0vnM9pncsuLXR9h+Znw=

**Comment by GaborPeto** [comment]
Same issue here and adding 
`maven { url 'https://jitpack.io' }`
did not fix the issue either.
(Trying to use 0.88.0 as 0.88.2 is not working on windows because of this issue: https://github.com/realm/realm-java/issues/2504)

**Comment by beeender** [comment]
@GaborPeto 0.88.0 and 0.88.2 should not have different results for issue #2504 . Do you use Realm in lib project?
