### ISSUE TITLE
RealmChangeListener not called for newly created objects

### ISSUE THREAD

**Issue by MGaetan89** [realm/realm-java#2748]
#### Goal

Get a row from a table (asynchronously) if it exists, or be notified when said row is created.
#### Expected Results

`RealmChangeListener` being called once when the query is done, with `object.isValid` set to `false` (the row is not in the table yet).
When the row is inserted, `RealmChangeListener` should be called a second time, with `object.isValid` set to `true`.
#### Actual Results

`RealmChangeListener` is called once, with `object.isValid` set to `false`, but not a second time after the object has been saved in the database.
#### Steps & Code to Reproduce

You can looks at [this class](https://github.com/MGaetan89/ShowsRage/blob/master/app/src/main/kotlin/com/mgaetan89/showsrage/fragment/StatisticsFragment.kt) for an example of implementation.
- In [`onCreate()`](https://github.com/MGaetan89/ShowsRage/blob/master/app/src/main/kotlin/com/mgaetan89/showsrage/fragment/StatisticsFragment.kt#L88) I read the data from the database (asynchronously, with a listener) and send a request to the server.
- In [`success()`](https://github.com/MGaetan89/ShowsRage/blob/master/app/src/main/kotlin/com/mgaetan89/showsrage/fragment/StatisticsFragment.kt#L142) I save the data received from the server in the database.
- In [`onChange()`](https://github.com/MGaetan89/ShowsRage/blob/master/app/src/main/kotlin/com/mgaetan89/showsrage/fragment/StatisticsFragment.kt#L40) I try to display the data if the `object` is valid.
#### Version of Realm and tooling

Realm version(s): 0.90.0
Android Studio version: 2.1

**Comment by beeender** [comment]
It seems to be a bug, i am checking now/

**Comment by beeender** [comment]
@MGaetan89 I am trying to play with you project. When i go to the `Statistics`, the spinner never stops so the `success()` hasn't been called. How can I reproduce the issue?

**Comment by MGaetan89** [comment]
Thanks for having a look @beeender.

The spinner stops when `onChange()` is called with a valid object.
On my side, `success()` is called, and the data are saved in Realm. But `onChange()` is not notified.
You need to have a running [SickRage](https://github.com/SickRage/SickRage) server somewhere to be able to use my app. Maybe that can be an issue on your side?

**Comment by beeender** [comment]
@MGaetan89 I tried to install the SikcRage and run with you app. But i got `index() got an unexpected keyword argument 'sort'` when sending http req. Maybe you have some quick answer?

**Comment by MGaetan89** [comment]
I don't know where that issue comes from.
I will try to provide a simple standalone project to reproduce the problem when I have a moment.

**Comment by MGaetan89** [comment]
Is it possible that my issue is similar to https://github.com/realm/realm-java/issues/2158?

**Comment by beeender** [comment]
But that one has been fixed long time ago?
Recently #2761 is kind of related with what you described. Maybe you can try the latest release?

**Comment by MGaetan89** [comment]
Sorry for the delay.
I tried with 0.90.1 and 0.91.0 and the issue is still here.
However, in a simple standalone I did to try to reproduce the issue, it is working fine. I will investigate more to see where this might come from.

**Comment by kneth** [comment]
@MGaetan89 Thanks for the update. In it works in a simple case, it is worth asking what the differences are between the simple case and the case failing?

**Comment by MGaetan89** [comment]
I pushed it [here](https://github.com/MGaetan89/Realm_2748) so you can have a look.
The mail class is [MainActivity](https://github.com/MGaetan89/Realm_2748/blob/master/app/src/main/java/io/realm/realm_2748/MainActivity.java).
Maybe I should have done it in Kotlin, to make sure it is not a language issue?

**Comment by cmelchior** [comment]
Hi @MGaetan89 I have been looking at your example, and I think I might have an explanation.

- It looks like you are using `findFirstAsync` and then add a changelistener to that.
- When you do the `findFirstAsync`, the Realm is empty = no object was found
- We still return a "dummy" loader object, but this will point to "nothing". This is why it is `loaded:true` and `valid:false`
- Adding a new object will not change the result of `findFirst`, that will still point to to the original object, which in your was was a "null" object.

It is actually a case we have been discussing internally earlier, but believed that the current behaviour is better as changing the object completely would be confusing to people. e.g. if you did findFirst on `[2,3,4]` you would get `2`, but if it was updated to `[1, 2, 3, 4]` your `2` would suddenly be come `1`.

In your case it sounds like what you are actually after is the `findAll().first()` instead of `findFirst()`

**Comment by MGaetan89** [comment]
Thanks for the clarification @cmelchior. Now I have a better understanding of what is happening.
However, I don't think that using `findAll().first()` is always a good solution (or the more intuitive).

If I do the query when the table is empty, `findFirst()` will return an empty list. So calling `first()` immediately will throw an Exception. (same if I use `findFirstAsync()` from my understanding of the source code).
In other falling cases in my app, I do a query based on a primary key. So it seems logical for me to do something like `equals("myPrimaryKeyField", value).findFirst()`, because I know that the object will always the one I want, no matter what happen in the database (unless the object is deleted). However, it is less intuitive to use `findAll().first()` in this case (even if it seems to be the recommended way).
Am I misunderstanding something here? Or is there something else I can try?

**Comment by cmelchior** [comment]
Hmm, yes, I can see why in that case you would expect the dummy object to eventually contain the real one. What is your use case since you know the primary key value before it was inserted in the Realm?

If we wanted to change `findFirst` to support this it would not be trivial as it would mean we had to do more advanced query and schema parsing to detect these cases, so right now I am leaning more towards just documenting the current behaviour better. What do you think @nhachicha @realm/java ?  

I guess the primary problem is how one think about "live-update" and what it means, e.g. does findFirst means "always point to the first object of a query" or does it mean "find the first object _now_ and keep that up to date". Right now Realm uses the second interpretation, but maybe the first use case could be supported through some some other API method?

**Comment by beeender** [comment]
Returning a dummy object first would be weird IMO. There will be lots of corner cases which are quite difficult to handle. eg.  PK1_object created -> PK1_object deleted -> PK1_object created again, in above there are actually two Independent objects involved, but from the primary key perspective, they are the same object.

For this case, I strongly think `RealmResults` and `findAll` should be used instead of `findFirst()`.

**Comment by MGaetan89** [comment]
@cmelchior My use case is as follow: I get a list of data from a server and save it in the database (each element has a Primary Key). I then display it to the user. The user can select one entry to display additional information about it.
Those information are also stored in the database, in separate tables, but with the same PK as the selected entry. So the first time, I know the PK I have to use, but there is no data yet.

For the moment, I am doing as you suggested: using `findAll()` and filtering the result in the listener once notified.

**Comment by njovy** [comment]
@cmelchior
```
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import io.realm.Realm;
import io.realm.RealmConfiguration;
import io.realm.RealmResults;

public class MainActivity extends AppCompatActivity {
  private static final String TAG = MainActivity.class.getSimpleName();
  Realm realm;

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    Realm.setDefaultConfiguration(
        new RealmConfiguration.Builder(this).deleteRealmIfMigrationNeeded().build());
    realm = Realm.getDefaultInstance();
    realm.setAutoRefresh(true);
    realm.where(User.class)
        .equalTo("id", 1L)
        .findFirstAsync()
        .asObservable()
        .filter(u -> u.isLoaded())
        .subscribe(u -> {
          Log.d(TAG, "findFirstAsync u=" + u);
        });

    realm.where(User.class)
        .equalTo("id", 1L)
        .findAllAsync()
        .asObservable()
        .filter(RealmResults::isLoaded)
        .subscribe(u -> {
          Log.d(TAG, "findAllAsync u=" + u.size());
        });

    for (int i = 0; i < 10; i++) {
      AsyncTask.SERIAL_EXECUTOR.execute(() -> {
        Realm realm = Realm.getDefaultInstance();
        realm.executeTransaction(r -> {
          User user = r.where(User.class).equalTo("id", 1).findFirst();
          if (user == null) {
            Log.d(TAG, "New User");
            r.copyToRealmOrUpdate(new User(1));
          } else {
            user.deleteFromRealm();
          }
        });
        realm.close();
        try {
          Thread.sleep(1000);
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
      });
    }
  }

  @Override protected void onDestroy() {
    super.onDestroy();
    realm.close();
  }
}
```
Above is the simple test code that you can check this issue.
findFirstAsync.asObservable.subscribe doesn't get called whenever it's deleted from realm or newly created to realm.

**Comment by njovy** [comment]
I replaced ```findFirstAsync``` with ```findAllAsync``` to detect any changes after reading this explanation.

**Comment by cmelchior** [comment]
After thinking about this some more, I am starting to come around to liking what @MGaetan89 is proposing more and more.

The reason being that we say everywhere that all our queries are "live". Except in the case of the `findFirst()` that is not really the case. True, the result of the query is "live", but the query itself is not. 

For `findAll` that distinction doesn't really exist, since both interpretations result in the same result, but for `findFirst()` it does matter.

Also the most common use case for findFirst is most likely finding an object using the primary key just like in this case, and right now I am having a hard time finding use cases that would break if we changed the behaviour.

What do you think @realm/java ? Especially the use case provided here: https://github.com/realm/realm-java/issues/2748#issuecomment-221791178 . If the Primary key is considered the interesting unique identifier, then it shouldn't matter if the object was deleted and addd again. 

E.g. you have the same behaviour for `findAll()` where objects can come and go.

**Comment by beeender** [comment]
This has been addressed by #4358 and #4367
