### ISSUE TITLE
failed to create temporary directory /data/user/0/xxx/files/.realm.temp

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4430]
Reported on SO http://stackoverflow.com/questions/43219226/realm-init-fails-data-user?noredirect=1#comment73512411_43219226

```java
Realm.init(this);
Realm.setDefaultConfiguration(new RealmConfiguration.Builder()
        .name("default.realm")
        .modules(Realm.getDefaultModule(), new RealmCoreModule())
        .schemaVersion(10)
        .migration(new SampleRealmMigration())
        .build());
```

> Fatal Exception: java.lang.RuntimeException: Unable to create application com.zappos.android.ZapposApplication: io.realm.internal.IOException: failed to create temporary directory: /data/user/0/com.zappos.android/files/.realm.temp at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4800) at android.app.ActivityThread.access$1600(ActivityThread.java:157) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5527) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) Caused by io.realm.internal.IOException: failed to create temporary directory: /data/user/0/com.sample.android/files/.realm.temp at io.realm.internal.SharedRealm.initialize(SharedRealm.java:48) at io.realm.Realm.init(Realm.java:191) at com.sample.android.SampleApplication.onCreate(SampleApplication.java:223) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4797) at android.app.ActivityThread.access$1600(ActivityThread.java:157) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5527) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

I've noticed that this fails sometimes and more regularly on LG devices on Android 6.

Disk space was not an issue and neither was RAM. From a little more research it says /data/user/0 is something that gets returned during multiple user profiles on the phone. I haven't had luck trying to replicate it.

**Comment by beeender** [comment]
Need some investigation, might be related with multi user profile?

**Comment by gaara87** [comment]
> classpath 'io.realm:realm-gradle-plugin:2.2.2'

**Comment by beeender** [comment]
I tested with multi user support on both emulator Android 7.0 & 6.0 with multi user accounts enabled.

@gaara87 
1. How many devices have this problem?
2. Is it only happen to Android 6?
3. Only on LG devices?
4. What are the LG device model and Rom version?

**Comment by gaara87** [comment]
1. 4 different devices
2. Yes its only on 6
3. Yes
4. LGMS631 is the most recurring device. I dont think they are custom rom, or atleast fabric doesn't inform if it is.

**Comment by beeender** [comment]
I think #4559 should fix this.
@gaara87 Would you please help to verify this when #4559 released? It will be released in `v3.1.4` and `v3.2.0` . Thanks.

**Comment by gaara87** [comment]
I'll update the version and will let you know 👍

**Comment by kevinjam** [comment]
@gaara87 did you fix the issue ?
@beeender the issue is still repeating on the last version :6.0.2
