### ISSUE TITLE
copyFromRealm(recipeRealmResult) freezing UI thread

### ISSUE THREAD

**Issue by RajendraSinghBohra** [realm/realm-java#4938]
I have 30k around data  and trying the search in the result. While I do copyFromRealm(recipeRealmResult) my Application get stuck for large data. 

`List<RecipeRealmObject> realmList = realm.copyFromRealm(recipeRealmResult); 
`

**Comment by Zhuinden** [comment]
Why are you copying from the Realm?

**Comment by RajendraSinghBohra** [comment]
@Zhuinden  I want to implement conditional sort in my application, for which I have implemented Comparator. for more details please check the following link. 
https://stackoverflow.com/questions/44963174/is-there-a-way-to-conditional-sort-in-two-fields-in-realm

**Comment by Zhuinden** [comment]
Ah ,you're the one who said https://stackoverflow.com/questions/34975080/complexe-sorting-for-search-in-realm/34976540#34976540 doesn't solve the problem, even though your problem can be solved by using an adapter that "concatenates" two RealmResults.

Well eagerly copying 30000 objects seems a bit excessive. I'd probably just concat the two RealmResults like I originally mentioned in my comment.

**Comment by Zhuinden** [comment]
You can see tricky solution here https://stackoverflow.com/a/45011334/2413303

**Comment by beeender** [comment]
@RajendraSinghBohra I also added another solution on SO https://stackoverflow.com/a/45011471/1396606

Let's discuss there since the `copyFromRealm()` won't the ideal solution for your problem. I am closing this issue now.

**Comment by RajendraSinghBohra** [comment]
Thanks @Zhuinden @beeender for the solution help. I will try these and get back on SO.  :)
