### ISSUE TITLE
App  crashes with FORMAT_UPGRADE_REQUIRED while using Realm 7.0.0

### ISSUE THREAD

**Issue by 73sravanthi** [realm/realm-java#6889]
We have been using Realm from the past year, We recently upgraded the application from V6.1.0 to V7.0.0, post this upgrade we are witnessing the crash mentioned, we are using Kotlin for application development with Realm java and lastly, we have enabled DB encryption

 Process: com.com.myapp.Application.qa, PID: 31558
    java.lang.RuntimeException: Unable to create application com.myapp.Application: io.realm.exceptions.RealmFileException: Opening Realm files of format version 0 is not supported by this version of Realm (Database has an unsupported version and cannot be upgraded
    Exception backtrace:
(/data/data/com.myapp.Application:/files/myapp.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: FORMAT_UPGRADE_REQUIRED.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
        at io.realm.BaseRealm.<init>(BaseRealm.java:137)
        at io.realm.BaseRealm.<init>(BaseRealm.java:104)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.createInstance(RealmCache.java:507)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:473)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:414)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)

**Comment by cmelchior** [comment]
How are you opening the Realm?

**Comment by 73sravanthi** [comment]
DB configuration :  
RealmLivedataWrapper.init(context)
    val config = RealmConfiguration.Builder()
      .name(BuildConfig.REALM_FILE_NAME)
      .modules(Realm.getDefaultModule(), DataRealmModules())
      .encryptionKey(StorageKeyUtils.getKey(sharedPreferences, context))
      .schemaVersion(BuildConfig.REALM_SCHEMA_VERSION)
      .migration(DbMigration())
      .build()
    Realm.setDefaultConfiguration(config)

    realmLivedataWrapper = RealmLivedataWrapper.Builder()
      .setRealmConfiguration(config)
      .build()

While navigating between the modules its crashing at 
  val realm: Realm = Realm.getDefaultInstance()

**Comment by cmelchior** [comment]
Weird. The error message seems to indicate that you are opening an older already existing file. Is that the case?

**Comment by 73sravanthi** [comment]
It's crashing while navigating from one module to another after some modifications. We have used Realm v6.1.0. This issue is observed when upgraded to v7.0.0 .

**Comment by 73sravanthi** [comment]
The same scenario is working fine with Realm v6.1.0

**Comment by 73sravanthi** [comment]
Will there be any issue if we use following  method in 7.0.0

   val realm: Realm = Realm.getDefaultInstance()
    realm.sharedRealm.refresh()
    try {
      realm.executeTransaction { realmInstance ->
        realmInstance.copyToRealmOrUpdate(dataObjects)
      }
    } catch (ex: Exception) {
      Log.d("DOWNLOAD_ERROR", "storeToLocal DB store EXCEPTION")
      Log.d(this::class.java.simpleName, ex.message)
    } finally {
      realm.refreshAndClose()
    }

**Comment by 73sravanthi** [comment]
Hi.Any update on the above issue? We are facing the above crash with above error in multiple places .

**Comment by edgar-zigis** [comment]
I have noticed this error too. We have only upgraded realm version and did not touch schema itself.
Mostly it occurs on Android 10 devices. Most popular devices which failed to upgrade:
```
Samsung Galaxy A70
Xiaomi Mi9 SE
Nokia 5
```
Other devices seemed to work fine, but this is quite critical.

**Comment by ganfra** [comment]
Exactly the same issue on our side, reproduced on my Pixel 3 on Android 9.

**Comment by cmelchior** [comment]
@ganfra Can you share how to reproduce? If you want to keep it private you can email me at christian.melchior@mongodb.com

**Comment by ganfra** [comment]
If you are brave enough you can test it on our open-source project: https://github.com/vector-im/riotX-android
Updating realm to 7.0.0, then after some initial launches it will crash with this issue.
(Also, not related at all, but we are having massive performance issues when db is getting big)

**Comment by ganfra** [comment]
So I created a test account where you will be able to reproduce the error:
Login: realm7
Password: realm7.0help

You should use the develop branch.

So here is how to reproduce
1. compile the app with realm 6.1.0 (in the matrix-sdk-android gradle file). 
2. launch and log in with given credentials. Maybe open some conversations.
3. kill the app and relaunch => it should crash. If not, kill and relaunch until it crashes

Tell me if you need more information :)

**Comment by ganfra** [comment]
@cmelchior : any chance you could look at it?

**Comment by cmelchior** [comment]
@ganfra Thank you for the project. I am able to reproduce the problem. We are looking into it.

**Comment by ganfra** [comment]
Did you have any lead on what could be wrong?

**Comment by patelnishantk** [comment]
@cmelchior Would appreciate any update on this. Unfortunately, we too face this issue after upgrading from v6.1.0 to v7.0.0. It has resulted into hundreds of crashes reported in Firebase in barely few hours.

**Comment by cmelchior** [comment]
@patelnishantk Unfortunately we still don't have a root cause for this.

**Comment by ppamorim** [comment]
We are experiencing the same issue with a single client.

**Comment by ppamorim** [comment]
@cmelchior We are going to extract the user database and analyse it to see if it's the realm running in the device that cannot open it or if the realm file is corrupted.

**Comment by ppamorim** [comment]
We got the Realm file and when opening it on Realm Studio, we get the very same error:

<img width="913" alt="Screenshot 2020-08-05 at 10 49 13" src="https://user-images.githubusercontent.com/5521682/89398693-60fb9780-d709-11ea-95d2-785e56612fa7.png">

**Comment by edgar-zigis** [comment]
@cmelchior

**Comment by cmelchior** [comment]
@ppamorim Is that a file you are able to share with us? You can send it to christian.melchior@mongodb.com to keep it confidential

**Comment by ppamorim** [comment]
@cmelchior For the moment, giving direct access, no. But I will try to find ways to share it with you. One thing I noticed is that the file is 707mb which is completely wrong. My superior told me that we can do remote access of the file.

**Comment by cmelchior** [comment]
Interesting. How do you know the filesize was wrong?

**Comment by ppamorim** [comment]
@cmelchior Based on the realm file size. I opened the encrypted realm in a hex editor and I can see a bunch of zeros in some situations. I am not sure if it's part of the paging or something. I will send the layout of the file shortly.

**Comment by cmelchior** [comment]
It could be yes. We will be making a new release with this fix shortly. Probably tomorrow.

**Comment by ppamorim** [comment]
@cmelchior Is there any way to run tests against the realm file that I have here by using the realm-core tests with this fix in place?

**Comment by cmelchior** [comment]
Yes, you can build Realm Java against source by adding the `-PcoreSourcePath=<pathToCore>` when building it, but if the file is already "broken" that fix is not going to help from my understanding.

**Comment by ppamorim** [comment]
@cmelchior I would rather try to open on Realm Studio.

**Comment by ppamorim** [comment]
@cmelchior Isn't it the case of migrating the realm file version + encrypted data migration of a huge file?

**Comment by cmelchior** [comment]
We released Realm Java 7.0.2 which we believe should fix this. Please reopen if this still happens after upgrading to that version.

**Comment by cmelchior** [comment]
@ppamorim If you cannot upgrade a huge file due to size, it should just abort opening the file.

**Comment by ganfra** [comment]
Hi there, it's still crashing on our side...

**Comment by cmelchior** [comment]
Hi @ganfra Thanks for info.

**Comment by ganfra** [comment]
What do you mean by old and new? 
I was using the app with realm 6.1.0 then I compiled with 7.0.2 and when lauching the app it crashes. I guess it's ok when there is no existent db.

**Comment by cmelchior** [comment]
@ganfra Is it something you can reproduce? We would be very interested in seeing the 6.1.0 Realm before the upgrade so we can figure out what exactly is going on

**Comment by ganfra** [comment]
I already gave you the info to reproduce, if you scroll up in the comments, you have the github project (riotx-android/element-android). It was crashing for 7.0.0, still there with 7.0.2 with the exact same procedure

**Comment by cmelchior** [comment]
Ah yes. Sorry :(

**Comment by ganfra** [comment]
No problem :)

**Comment by jedelbo** [comment]
At some point there was a problem with the combination of encryption and compactOnLaunch. It was fixed just recently. Could this be what we are seeing here?

**Comment by edualonso** [comment]
@ganfra is this still an issue with 7.0.3?

**Comment by ganfra** [comment]
Tested right now, still crashing (done twice, crashed twice too)

**Comment by clementetb** [comment]
@ganfra Would you mind trying version 7.0.4, we released it today.

**Comment by finnschiermer** [comment]
@ganfra Trying 7.0.5 would be even better.

**Comment by ganfra** [comment]
Just tried 7.0.5, still no chance with it...

**Comment by jedelbo** [comment]
@ganfra  I you have a file that producers this error when opened, we cannot fix this with  a new version. If the file has a file format of '0' it cannot be opened. So what we need to focus on is how we ended up in this situation. Are you able to produce new files where this is a problem?

**Comment by jedelbo** [comment]
We have found the root cause for this error.

**Comment by ganfra** [comment]
Any idea when we'll get a new release with this fix? :)

**Comment by jedelbo** [comment]
Fix has been committed. It will take e few days for that to reach the Java binding.

**Comment by ppamorim** [comment]
@ganfra Be aware that already corrupted databases won't be restored. We had to create a special app to export critical data from our apps. Far from ideal and a bit humiliating. :( I would like to see the Realm team speaking more about it. @jedelbo Could you please refer to the PR? Was it in the core?

**Comment by jedelbo** [comment]
Be aware that the file is not corrupted.We just fail to read the file correctly. The issue was fixed in https://github.com/realm/realm-core/pull/3910.

**Comment by ppamorim** [comment]
@jedelbo I did export 3 databases + encryption keys and I could not open any of them on Realm Studio. All of them where around 700mb for an unknown reason. That's why I suspect that the file was corrupt.

**Comment by ganfra** [comment]
Same issue of 700mb size, but I did manage to see this issue before releasing the app, so no problem for me...

**Comment by jedelbo** [comment]
@ganfra so you see an unexpected increase in size? How big a difference is there compared to earlier?

**Comment by ganfra** [comment]
Generally the file is 150mb in this usecase. Multiple time after this crash it grows to 700mb as I said.

**Comment by ppamorim** [comment]
@jedelbo Could you please confirm if the latest version is capable of opening these large databases and if it's able to reduce it's size?

**Comment by jedelbo** [comment]
The Java team is working out getting the release out later today.

We are able to handle realms of any practical size. You can use CompactOnLaunch to reduce the size of a realm. However we are of course interested in keeping the size of the realm down, so we would be interested in investigating why you experience this growth in size. So would you be willing and able to share a 'before' and 'after' realm with us? You can share the files privately by mail (jorgen.edelbo@mongodb.com).

**Comment by ppamorim** [comment]
I think @ganfra will be able to provide a database, I could not replicate the issue on my side and the data that I have cannot be shared.

**Comment by ppamorim** [comment]
@jedelbo Any update?

**Comment by ppamorim** [comment]
@cmelchior The version 7.0.2 didn't sort the issue. We are going to update it to version 7.0.5. The situation is bad.

**Comment by cmelchior** [comment]
We will be making a 7.0.6 release in the next few hours that should have a fix for this.

**Comment by jedelbo** [comment]
You should wait for v7.0.6. It should be just around the corner.

**Comment by prettyClouds** [comment]
Is there any kind of public pipeline we can monitor to get an idea of when things will release?

**Comment by cmelchior** [comment]
You can watch releases on Bintray here: https://bintray.com/realm/maven/realm-android-library

**Comment by cmelchior** [comment]
7.0.6 was just released which should fix this. Please reopen the issue if you still see it after upgrading.

**Comment by ppamorim** [comment]
@cmelchior The version 7.0.6 is still not available, any timeframe or workaround for the moment?

**Comment by cmelchior** [comment]
It should be available now.

**Comment by ganfra** [comment]
Ok so now I can't reproduce, looking good! Thanks for this long-awaited fix!

**Comment by ppamorim** [comment]
@ganfra Hi, were you able to open that 700mb realm file too?

**Comment by ganfra** [comment]
Didn't try, but I got a SEGFAULT 11 and a corrupted file just after, so shout victory too quickly...

**Comment by ppamorim** [comment]
@ganfra Very nice, imagine to live in a world where the database of your application gets corrupted due a bug.

**Comment by ppamorim** [comment]
@ganfra Some users were able to restore the app. I got one case where the app wasn't able to load the database.

**Comment by ganfra** [comment]
@ppamorim thanks for letting me know, but I just keep getting native crashes on some other parts

**Comment by sampathkumar1988** [comment]
Hi Team, We are getting this crash in our production. Not able to reproduce though. Any solutions ?

**CRASH TYPE SUMMARY**
**LOCATION**
SourceFile line -2 in io.realm.internal.OsSharedRealm.nativeGetSharedRealm()
**EXCEPTION**
io.realm.exceptions.RealmFileException
**MESSAGE**
Opening Realm files of format version 22 is not supported by this version of Realm (Database has an unsupported version and cannot be upgraded Exception backtrace: <backtrace not supported on this platform>) (/data/data/com.company.au.gma/files/company-sdk-account.storage) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107


Note: We are using the 7.0.8 realm version

Thanks

**Comment by jedelbo** [comment]
@sampathkumar1988 Seems like you are opening a file produced by a newer version of realm with a rather old version.
