### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kutran** [realm/realm-java#6995]
#### Goal
Stable app without crashes on startup.

#### Actual Results
Crash on startup.

#### Steps & Code to Reproduce
1. Install app
2. Start app
3. Notice the crash

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.myapp.test <<<

backtrace:

  #00  pc 000000000017ec6c  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #01  pc 000000000017fbe7  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #02  pc 000000000017eba5  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #03  pc 00000000001407ff  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #04  pc 000000000014085f  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #05  pc 000000000017eab3  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #06  pc 00000000001407ff  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #07  pc 000000000014085f  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #08  pc 00000000000b7589  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #09  pc 00000000000bee71  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #10  pc 00000000000c7713  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #11  pc 00000000000c76c9  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #12  pc 00000000000c96f7  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #13  pc 00000000000c9b51  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #14  pc 00000000000d8ef1  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #15  pc 00000000000d9517  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #16  pc 00000000000c818b  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so
  #17  pc 00000000000728df  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/lib/arm/librealm-jni.so (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+42)
  #18  pc 000000000022cecb  /data/app/com.myapp.test-U2Y6LEmadD-4p1lvjmadmA==/oat/arm/base.odex (offset 0xbf000)
```
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.myapp.test <<<

backtrace:
  #00  pc 0000000000083134  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
  #01  pc 000000000034b6c4  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so (__gnu_cxx::__verbose_terminate_handler()+348)
  #02  pc 000000000031b0cc  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so (__cxxabiv1::__terminate(void (*)())+8)
  #03  pc 000000000034b390  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #04  pc 000000000031a950  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so (__gxx_personality_v0+192)
  #05  pc 000000000035f138  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #06  pc 000000000035f650  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so (_Unwind_Resume+116)
  #07  pc 0000000000190594  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #08  pc 0000000000190cb0  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #09  pc 000000000018fb34  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #10  pc 000000000018fb98  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #11  pc 0000000000206494  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #12  pc 0000000000208b80  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #13  pc 0000000000209220  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #14  pc 000000000020ba58  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #15  pc 0000000000155b80  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #16  pc 0000000000156730  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #17  pc 0000000000174b28  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #18  pc 0000000000175a88  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #19  pc 000000000015414c  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so
  #20  pc 00000000000cbc30  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/lib/arm64/librealm-jni.so (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+540)
  #21  pc 0000000000041d74  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.odex (art_jni_trampoline+180)
  #22  pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568)
  #23  pc 000000000014608c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276)
  #24  pc 00000000002e0c94  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #25  pc 00000000002dbf74  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912)
  #26  pc 000000000059cc50  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368)
  #27  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #28  pc 00000000007d1d9a  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.<init>+94)
  #29  pc 000000000059c744  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #30  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #31  pc 00000000007d1f74  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.getInstance+48)
  #32  pc 000000000059cf50  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #33  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #34  pc 0000000000472674  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.a.<init>+164)
  #35  pc 000000000059c744  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #36  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #37  pc 00000000004725b4  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.a.<init>+4)
  #38  pc 000000000059c744  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #39  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #40  pc 00000000007d5162  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.n.<init>+34)
  #41  pc 000000000059c744  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #42  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #43  pc 00000000007d5268  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.n.a+4)
  #44  pc 000000000059cf50  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #45  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #46  pc 0000000000476f66  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.p.b+478)
  #47  pc 000000000059c744  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #48  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #49  pc 0000000000476a12  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.p.a+14)
  #50  pc 000000000059cf50  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #51  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #52  pc 00000000007d5428  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.n.b+8)
  #53  pc 000000000059cf50  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #54  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #55  pc 00000000004765de  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.n$1.run+26)
  #56  pc 000000000059bba8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740)
  #57  pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #58  pc 0000000000474aaa  /data/app/com.myapp.test-bcyQ5vDo6bZvYrHhwyWm4g==/oat/arm64/base.vdex (io.realm.internal.async.a.run+14)
  #59  pc 00000000002b18e0  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.18252570399552585066)+240)
  #60  pc 000000000058b6ac  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
  #61  pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
  #62  pc 0000000000201f34  /system/framework/arm64/boot.oat (java.util.concurrent.Executors$RunnableAdapter.call+68)
  #63  pc 0000000000298d08  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+200)
  #64  pc 00000000002fa878  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+984)
  #65  pc 00000000002f7ee0  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
  #66  pc 00000000001a5568  /system/framework/arm64/boot.oat (java.lang.Thread.run+72)
  #67  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #68  pc 000000000014606c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #69  pc 00000000004ab6f0  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #70  pc 00000000004ac784  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #71  pc 00000000004ecac4  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #72  pc 00000000000e28c0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #73  pc 000000000008503c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:6.0.0

Realm Sync feature enabled: No

Android Studio version: 4.0

Android Build Tools version: 28.0.3

Gradle version: 6.1.1

Which Android version and device(s):
- Android 10, Samsung Galaxy S8 (dreamqltesq)
- Android 10, Samsung Galaxy S8+ (dream2qltesq)
- Android 10, Samsung Galaxy A20 (a20p)

**Comment by cmelchior** [comment]
@kutran There should also be an exception message above the `****` line? Do you have that as well?

**Comment by kutran** [comment]
Unfortunately, these crash reports are from Google Play Vitals, so there isn't any more information before the **** line.

**Comment by MeinLieberScholli** [comment]
I'm having the same issue.

In my case, it affects mostly Samsung Galaxy S8 and S8+ users with Android 9.
It started after updating to realm 7.0.0.
Crashlytics is not showing these crashes, only Android Vitals.
![image](https://user-images.githubusercontent.com/9082911/87551308-76544780-c6b0-11ea-92d3-0bdb70c22891.png)

This bug is occuring periodically, so i'm assuming it has something to do with my BroadcastReceiver that is triggered by the AlarmManager. However, i can't find a bug there yet.

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.best.fit <<<

backtrace:
  #00  pc 0000000000021d94  /system/lib64/libc.so (abort+124)
  #01  pc 00000000002b21b4  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #02  pc 00000000002b2234  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #03  pc 00000000002b2358  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #04  pc 000000000023bd74  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #05  pc 000000000023bc38  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #06  pc 0000000000253a98  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #07  pc 00000000001e974c  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #08  pc 00000000001e9690  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #09  pc 00000000001e2d04  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #10  pc 000000000028dfe4  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #11  pc 00000000002514a8  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #12  pc 0000000000255f88  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #13  pc 0000000000255118  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #14  pc 0000000000256140  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #15  pc 0000000000258420  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #16  pc 000000000018a2b0  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #17  pc 0000000000189df0  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #18  pc 0000000000189d74  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #19  pc 0000000000176040  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000)
  #20  pc 000000000011f07c  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/split_config.arm64_v8a.apk (offset 0x1000) (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+132)
  #21  pc 0000000000053014  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.odex (offset 0x51000) (io.realm.internal.OsObject.nativeCreateNewObjectWithStringPrimaryKey [DEDUPED]+196)
  #22  pc 000000000056224c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #23  pc 00000000000d0160  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #24  pc 00000000002865e8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
  #25  pc 00000000002816b0  /system/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+752)
  #26  pc 0000000000533f54  /system/lib64/libart.so (MterpInvokeStaticRange+148)
  #27  pc 0000000000554a94  /system/lib64/libart.so (ExecuteMterpImpl+15380)
  #28  pc 0000000000b9b8f4  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.<init>+108)
  #29  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #30  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #31  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #32  pc 0000000000532580  /system/lib64/libart.so (MterpInvokeDirect+296)
  #33  pc 0000000000554714  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #34  pc 0000000000b9b6be  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.getInstance+26)
  #35  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #36  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #37  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #38  pc 0000000000532744  /system/lib64/libart.so (MterpInvokeStatic+204)
  #39  pc 0000000000554794  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #40  pc 0000000000b75d14  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.BaseRealm.<init>+176)
  #41  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #42  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #43  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #44  pc 0000000000532580  /system/lib64/libart.so (MterpInvokeDirect+296)
  #45  pc 0000000000554714  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #46  pc 0000000000b75c48  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.BaseRealm.<init>+8)
  #47  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #48  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #49  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #50  pc 0000000000532580  /system/lib64/libart.so (MterpInvokeDirect+296)
  #51  pc 0000000000554714  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #52  pc 0000000000b80e10  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.Realm.<init>+24)
  #53  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #54  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #55  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #56  pc 0000000000532580  /system/lib64/libart.so (MterpInvokeDirect+296)
  #57  pc 0000000000554714  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #58  pc 0000000000b8086c  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.Realm.createInstance+4)
  #59  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #60  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #61  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #62  pc 0000000000532744  /system/lib64/libart.so (MterpInvokeStatic+204)
  #63  pc 0000000000554794  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #64  pc 0000000000b7bc44  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.RealmCache.createInstance+8)
  #65  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #66  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #67  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #68  pc 0000000000532580  /system/lib64/libart.so (MterpInvokeDirect+296)
  #69  pc 0000000000554714  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #70  pc 0000000000b7b80a  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.RealmCache.doCreateRealmOrGetFromCache+234)
  #71  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #72  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #73  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #74  pc 0000000000532580  /system/lib64/libart.so (MterpInvokeDirect+296)
  #75  pc 0000000000554714  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #76  pc 0000000000b7b6da  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.RealmCache.createRealmOrGetFromCache+22)
  #77  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #78  pc 0000000000521980  /system/lib64/libart.so (artQuickToInterpreterBridge+1032)
  #79  pc 000000000056b0fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
  #80  pc 000000000056224c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #81  pc 00000000000d0160  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #82  pc 00000000002865e8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
  #83  pc 00000000002805a4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+948)
  #84  pc 0000000000532744  /system/lib64/libart.so (MterpInvokeStatic+204)
  #85  pc 0000000000554794  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #86  pc 0000000000b80934  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (io.realm.Realm.getInstance+8)
  #87  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #88  pc 000000000025fc20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #89  pc 0000000000280588  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #90  pc 0000000000532744  /system/lib64/libart.so (MterpInvokeStatic+204)
  #91  pc 0000000000554794  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #92  pc 000000000024354a  /data/app/com.best.fit-65omDsXmBizcSL_Wvwid3Q==/oat/arm64/base.vdex (com.best.fit.App.onCreate+122)
  #93  pc 000000000025a0a0  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2089273699)+496)
  #94  pc 0000000000521980  /system/lib64/libart.so (artQuickToInterpreterBridge+1032)
  #95  pc 000000000056b0fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
  #96  pc 00000000007f4644  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (android.app.Instrumentation.callApplicationOnCreate+52)
  #97  pc 00000000008fb388  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (android.app.ActivityThread.handleBindApplication+7448)
  #98  pc 00000000008f6360  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (android.app.ActivityThread$H.handleMessage+6960)
  #99  pc 0000000000b25324  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (android.os.Handler.dispatchMessage+180)
  #100  pc 0000000000b28420  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (android.os.Looper.loop+1264)
  #101  pc 0000000000901b28  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (android.app.ActivityThread.main+680)
  #102  pc 000000000056224c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #103  pc 00000000000d0160  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #104  pc 00000000004682e0  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #105  pc 0000000000469d38  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
  #106  pc 00000000003f87b8  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+48)
  #107  pc 000000000011e7e4  /system/framework/arm64/boot.oat (offset 0x114000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
  #108  pc 0000000000e0ff48  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
  #109  pc 0000000000e16af0  /system/framework/arm64/boot-framework.oat (offset 0x41f000) (com.android.internal.os.ZygoteInit.main+2208)
  #110  pc 000000000056224c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #111  pc 00000000000d0160  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #112  pc 00000000004682e0  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #113  pc 0000000000467f38  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+416)
  #114  pc 000000000036ab24  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+644)
  #115  pc 00000000000b9d10  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
  #116  pc 00000000000bc8d4  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+780)
  #117  pc 0000000000004990  /system/bin/app_process64 (main+1200)
  #118  pc 00000000000b0550  /system/lib64/libc.so (__libc_init+88)`

**Comment by MGaetan89** [comment]
I'm having the same crashes since I've updated to Realm 7.0.1.
Can I downgrade to Realm 7.0.0 until this issue is fixed, or is there some incompatibility between the two versions that could prevent me from doing this?

**Comment by strooooke** [comment]
I'd avoid 7.0.0; that one has #6875

**Comment by MGaetan89** [comment]
I've tried to downgrade to version 7.0.0 anyway, with no luck.
A lot of our users have to reinstall our application in order to use it.
Is there a workaround or a fix in progress?

**Comment by johnsabilla** [comment]
@MGaetan89 Have you tried 7.0.1?

**Comment by diogochbittencourt** [comment]
@johnsabilla same error.

**Comment by mattfiocca** [comment]
Am seeing this also on Samsung Active Tab 2, Android 8.1

**Comment by MGaetan89** [comment]
In the end, I downgraded Realm back to version 6.1.0, as suggested [here](https://github.com/realm/realm-java/issues/6992#issuecomment-658612022):
> In terms of downgrading, then you cannot downgrade an upgraded file, but if you delete the file, then it should be possible to downgrade. Not sure if that is an option for you?

And so far it seems to work as expected.

**Comment by beczesz** [comment]
Do you have an idea what can I do if some of our users already updated their realm db format to 7.0.X?
I can't just revert to 6.1.0 and publish a new build. Crashes are happening now very frequently and users can no longer open up the app...

**Comment by MGaetan89** [comment]
Did you try what's suggested in the [comment I linked](https://github.com/realm/realm-java/issues/6995#issuecomment-671049129)?

**Comment by beczesz** [comment]
Thank you for the reply, yes we were bouncing between the two possible solutions.
1. The one you suggested : the advantage is that 6.1.0 is stable. The downside is that the users who already migrated to the new db format (one like 10% of the users corrupt the database file during the update) I will have to delete their databases which has already in format of 7.0.X) Which is not really a good solution.

2. The other is that we will not revert, but somehow we figure out who has a corrupted database and only for those we delete them. So eventually every user will migrate to 7.0.X format. This is what I'm working on right now

**Comment by ninaniiranen** [comment]
I'm seeing similar crashes on a lot of devices

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.getdreams <<<

backtrace:
  #00  pc 0000000000083360  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176)
  #00  pc 00000000002b2cb8  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000002b2d38  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000002b2e5c  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000023bfa8  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000023be6c  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 0000000000253f90  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000001e9980  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000001e98c4  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000001e2f38  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000028d8a0  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 0000000000251760  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000002569b0  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 0000000000255b78  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 0000000000256b68  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 0000000000258e80  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000018a848  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000018a388  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000018a30c  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 00000000001765d8  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000)
  #00  pc 000000000011f07c  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0xde0000) (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+132)
  #00  pc 00000000000e5904  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.odex (art_jni_trampoline+196)
  #00  pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 00000000001460cc  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276)
  #00  pc 00000000002e35d8  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #00  pc 00000000002df6d0  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+656)
  #00  pc 00000000005a7c34  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStaticRange+236)
  #00  pc 0000000000131c94  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static_range+20)
  #00  pc 0000000000f8cb4c  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.<init>+108)
  #00  pc 00000000005a48c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000f8c9e8  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.getInstance+26)
  #00  pc 00000000005a50c8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #00  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #00  pc 0000000000f52a7a  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.a.<init>+186)
  #00  pc 00000000005a48c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000f52b0c  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.a.<init>+8)
  #00  pc 00000000005a48c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000f4a388  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.Realm.<init>+24)
  #00  pc 00000000005a48c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000f49f92  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.Realm.a+4)
  #00  pc 00000000005a50c8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #00  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #00  pc 0000000000f921e8  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.v.a+8)
  #00  pc 00000000005a48c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000f91dc8  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.v.b+234)
  #00  pc 00000000005a48c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000f91cb0  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.v.a+22)
  #00  pc 00000000002b3f08  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.16017486636107417700)+240)
  #00  pc 00000000005936c0  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024)
  #00  pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
  #00  pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 00000000001460cc  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276)
  #00  pc 00000000002e35d8  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #00  pc 00000000002de664  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+900)
  #00  pc 00000000005a4dc8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368)
  #00  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #00  pc 0000000000f49fa6  /data/app/com.getdreams-xR1oQ-sPr7io4PS19-PUwQ==/oat/arm64/base.vdex (io.realm.Realm.b+8)
  #00  pc 00000000005a50c8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #00  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
```

Seen on:
Samsung Galaxy S8
Samsung Galaxy S8+
Samsung Galaxy Note8
Samsung Galaxy S9
Samsung Galaxy S9+
Samsung Galaxy S10+
Samsung Galaxy S10e
Samsung Galaxy S10

Running Android 9 and 10.

**Comment by cmelchior** [comment]
We just released 7.0.2 with a number of bug fixes. We have reason to believe this issue was fixed. Unfortunately, we have not been able to reproduce it yet. But any feedback after upgrading to 7.0.2 would be appreciated.

**Comment by ninaniiranen** [comment]
I'm still seeing the issue

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.getdreams <<<

backtrace:
  #00  pc 0000000000021f6c  /system/lib64/libc.so (abort+116)
  #00  pc 00000000002b2720  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 00000000002b27a0  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 00000000002b28c4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000023bfd4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000023beb8  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 0000000000254168  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 00000000001e99ac  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 00000000001e98f0  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 00000000001e2f64  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000028d3e8  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 0000000000251874  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 0000000000256bd4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 0000000000255d94  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 0000000000256d8c  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 00000000002590b4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000018a8ac  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000018a3ec  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000018a370  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 0000000000176658  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000)
  #00  pc 000000000011f0a0  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/split_config.arm64_v8a.apk (offset 0xde0000) (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+132)
  #00  pc 0000000000083e04  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.odex (offset 0x7e000) (io.realm.internal.OsObject.nativeCreateNewObjectWithStringPrimaryKey [DEDUPED]+196)
  #00  pc 000000000055a64c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #00  pc 00000000000d00e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #00  pc 00000000002834c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
  #00  pc 000000000027e5ec  /system/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+748)
  #00  pc 000000000052c7f8  /system/lib64/libart.so (MterpInvokeStaticRange+148)
  #00  pc 000000000054cf14  /system/lib64/libart.so (ExecuteMterpImpl+15380)
  #00  pc 00000000010d4868  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.<init>+108)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052ae24  /system/lib64/libart.so (MterpInvokeDirect+296)
  #00  pc 000000000054cb94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #00  pc 00000000010d4632  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.internal.OsSharedRealm.getInstance+26)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052afe8  /system/lib64/libart.so (MterpInvokeStatic+204)
  #00  pc 000000000054cc14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #00  pc 0000000001094116  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.a.<init>+186)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052ae24  /system/lib64/libart.so (MterpInvokeDirect+296)
  #00  pc 000000000054cb94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #00  pc 00000000010941c4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.a.<init>+8)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052ae24  /system/lib64/libart.so (MterpInvokeDirect+296)
  #00  pc 000000000054cb94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #00  pc 000000000108a1c4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.Realm.<init>+24)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052ae24  /system/lib64/libart.so (MterpInvokeDirect+296)
  #00  pc 000000000054cb94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #00  pc 00000000010899fc  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.Realm.a+4)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052afe8  /system/lib64/libart.so (MterpInvokeStatic+204)
  #00  pc 000000000054cc14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #00  pc 00000000010de9d4  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.v.a+8)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052ae24  /system/lib64/libart.so (MterpInvokeDirect+296)
  #00  pc 000000000054cb94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #00  pc 00000000010de512  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.v.b+234)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052ae24  /system/lib64/libart.so (MterpInvokeDirect+296)
  #00  pc 000000000054cb94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #00  pc 00000000010de3e2  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.v.a+22)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000051a378  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
  #00  pc 00000000005634fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
  #00  pc 000000000055a64c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #00  pc 00000000000d00e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #00  pc 00000000002834c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
  #00  pc 000000000027d4c8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
  #00  pc 000000000052afe8  /system/lib64/libart.so (MterpInvokeStatic+204)
  #00  pc 000000000054cc14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
  #00  pc 0000000001089a1c  /data/app/com.getdreams-vGjdCWR08oPpMQZwWWxhIw==/oat/arm64/base.vdex (io.realm.Realm.b+8)
  #00  pc 00000000002571cc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.2026799985)+488)
  #00  pc 000000000025ccc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #00  pc 000000000027d4ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #00  pc 000000000052afe8  /system/lib64/libart.so (MterpInvokeStatic+204)
  #00  pc 000000000054cc14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
```

From:
Samsung Galaxy A40
Samsung Galaxy Note8
Samsung Galaxy S9+
Samsung Galaxy S10
Running Andorid 9 and 10.

**Comment by ninaniiranen** [comment]
I am getting another crash into crashlytics with 7.0.2, and it's pointing to a line where we do `Realm.getInstance(config).use { realm -> realm.where(DataClass::class.java).findFirst()?.id }` in our code. The odd thing is that we have already accessed the realm db in a similar manner once before the line crashlytics is reporting.

Samsung Galaxy A8(2018), Android 9:
```
Caused by java.lang.IllegalArgumentException: Illegal Argument: Attempted to insert null into non-nullable column
Exception backtrace:
<backtrace not supported on this platform>
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
       at io.realm.BaseRealm.<init>(BaseRealm.java:137)
       at io.realm.BaseRealm.<init>(BaseRealm.java:104)
       at io.realm.Realm.<init>(Realm.java:163)
       at io.realm.Realm.createInstance(Realm.java:499)
       at io.realm.RealmCache.createInstance(RealmCache.java:507)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:473)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:414)
       at io.realm.Realm.getInstance(Realm.java:428)
``` 

The message seems similar to the issue in #7025

**Comment by cmelchior** [comment]
@ninaniiranen Thank you for that. It seems to be the same bug as described here: https://github.com/realm/realm-core/issues/3836

**Comment by beczesz** [comment]
Ok, we decided that we will roll back to 6.1.0 for every user because 7.X and 10.X was unstable. We saw this especially on Samsung devices and OnPlus devices, but on others too. The database got corrupted on: schema migration, realm file format migration, and simply by using it after a while it got corrupted after a while. 

If anybody is interested how we did it then please let me a message.

**Comment by jedelbo** [comment]
@beczesz Is this case where Sync is involved?

**Comment by edualonso** [comment]
Closing due to inactivity. We believe all issues have been fixed. If it isn't the case for the one first reported, please reopen this ticket. For all others (@ninaniiranen,  @mattfiocca, @diogochbittencourt, @MGaetan89, @MeinLieberScholli) please create new issues and we will track them separately as it appears to us they are not caused by the same native crash. We risk making a huge snowball if we keep track of everything in this one ticket.
